(function(){
  'use strict';
  const $=id=>document.getElementById(id),D=window.FishingBaitRanking?.prepare(window.FISHING_DATA,window.FISHING_BAIT_CATCHES)||window.FISHING_DATA,E=window.FishingBook,S=window.FishingCollection;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const known=new Set(D?.fishes.map(f=>f.id)||[]),kinds={rod:'어류도감',spear:'작살도감'};
  let M,comparison,strategy,caught=new Set(),kind='rod',page=1,filtered=[],pageFish=[],groups=[],history=[],detailId=null,lastCollectionStamp='';
  const read=()=>S.read(localStorage);
  const link=(url,label)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;
  const tcFish=f=>`https://ffxivteamcraft.com/db/ko/item/${f.id}`;
  const number=f=>`${kinds[f.kind]||'조건용 어종'} ${f.order?'No.'+f.order:''}`;
  function notify(message){$('noticeText').textContent=message;$('notice').hidden=false;$('undo').hidden=!history.length;}
  function counts(){
    for(const type of ['rod','spear']){const count=D.fishes.filter(f=>f.kind===type&&caught.has(f.id)).length;$(`${type}Count`).textContent=`${count.toLocaleString()} / ${D.counts[type].toLocaleString()}`;$(`${type}Progress`).max=D.counts[type];$(`${type}Progress`).value=count;}
    const count=[...caught].filter(id=>known.has(id)).length;$('totalCount').textContent=`${count.toLocaleString()} / ${D.count.toLocaleString()}`;$('recordCount').textContent=`수집 ${count.toLocaleString()}종`+(caught.size>count?` · 현재 목록 밖 ID ${caught.size-count}개 보존`:'');
    $('markPage').disabled=!pageFish.some(f=>!caught.has(f.id));
    const stamp=[...caught].sort((a,b)=>a-b).join(',');if(stamp!==lastCollectionStamp){lastCollectionStamp=stamp;document.dispatchEvent(new CustomEvent('fishing-collection-changed'));}
  }
  function updateChecks(){for(const b of document.querySelectorAll('[data-caught]')){const has=caught.has(+b.dataset.caught);b.setAttribute('aria-pressed',String(has));b.closest('.fish-tile,.fish-row')?.classList.toggle('is-caught',has);const state=b.querySelector('.fish-state');if(state)state.textContent=has?'✓':'○';else b.textContent=b.closest('.plan-card')?'수집':has?'✓ 수집 완료':'수집 체크';}for(const s of document.querySelectorAll('[data-related-state]'))s.textContent=caught.has(+s.dataset.relatedState)?'✓ 수집':'미수집';}
  function save(changes,message,remember=true){try{const next=read(),before=[];for(const [id,value] of changes){if(!known.has(id)||next.has(id)===value)continue;before.push([id,next.has(id)]);if(value)next.add(id);else next.delete(id);}if(before.length){S.write(localStorage,next);if(remember){history.push(before);if(history.length>25)history.shift();}}caught=next;counts();updateChecks();if($('status').value!=='all')$('refreshResults').hidden=false;notify(message);return true;}catch{notify('저장하지 못했어요. 기존 기록은 그대로입니다. 브라우저 저장 권한·공간을 확인해 주세요.');return false;}}
  function merge(ids,message){try{const latest=read(),next=new Set([...latest,...ids]),before=[...ids].filter(id=>!latest.has(id)).map(id=>[id,false]);if(before.length){S.write(localStorage,next);history.push(before);}caught=next;counts();updateChecks();refilter();notify(message);return true;}catch{notify('기록을 저장하지 못했어요. 기존 기록을 덮어쓰지 않았습니다.');return false;}}
  const options=()=>({kind,query:$('search').value,status:$('status').value,region:$('region').value,bait:$('bait').value,rarity:$('rarity').value});
  function refilter(){filtered=M.filter(caught,options());page=1;$('refreshResults').hidden=true;render();}
  function reset(){for(const id of ['status','region','bait','rarity'])$(id).value='all';$('search').value='';refilter();}
  function chooseKind(type){kind=type;for(const t of ['rod','spear'])$(t+'Mode').setAttribute('aria-pressed',String(t===kind));$('baitViewOption').disabled=kind==='spear';$('baitField').hidden=kind==='spear';$('rarityField').hidden=kind==='spear';$('kindNote').hidden=kind!=='spear';$('bait').value='all';$('rarity').value='all';$('region').value='all';if(kind==='spear'&&$('view').value==='bait')$('view').value='spot';fillRegions();refilter();}
  function fillRegions(){const names=[...new Set(D.fishes.filter(f=>f.kind===kind).flatMap(f=>f.routes.map(r=>D.spots[r.spotKey].region)))].sort((a,b)=>a.localeCompare(b,'ko'));$('region').innerHTML='<option value="all">모든 지역</option>'+names.map(n=>`<option>${esc(n)}</option>`).join('');}
  function tile(f){
    const places=[...new Set(f.routes.map(r=>D.spots[r.spotKey]?.name).filter(Boolean))],baits=[...new Set(f.routes.flatMap(r=>M.paths(r).filter(p=>p.complete).map(p=>M.byId.get(p.ids[0])?.name)).filter(Boolean))];
    const placeText=places.slice(0,2).join(' · ')+(places.length>2?' 외 '+(places.length-2)+'곳':''),baitText=f.kind==='spear'?'작살질 · 미끼 없음':baits.length?'시작 미끼: '+baits.slice(0,3).join(' · ')+(baits.length>3?' 외 '+(baits.length-3)+'종':''):'미끼 자료 확인 필요';
    return `<article class="fish-tile"><button class="tile-check" data-caught="${f.id}" aria-pressed="false" aria-label="${esc(number(f)+' '+f.name)} 수집"><span class="tile-top"><span>${f.order}</span><span class="fish-state">○</span></span><img src="${esc(f.icon)}" alt="" width="42" height="42" loading="lazy"><strong title="${esc(f.name)}">${esc(f.name)}</strong></button><div class="collection-row-info"><span>${esc(placeText||'낚시터 확인 필요')}</span><small>${esc(baitText)}</small></div><button class="tile-detail" data-fish-detail="${f.id}" aria-label="${esc(f.name)} 낚시 조건">낚시 조건 ↗</button></article>`;
  }
  function reference(id){const f=M.byId.get(id);if(!f)return `<span>물고기 ${id}</span>`;return `<button class="related-fish" data-fish-detail="${id}">${esc(f.name)}${known.has(id)?` <span data-related-state="${id}">${caught.has(id)?'✓ 수집':'미수집'}</span>`:''}</button>`;}
  function baitPaths(route,base,fish){
    const paths=M.tacklePaths(route).filter(p=>!base||p.complete&&String(p.ids[0])===base);if(!paths.length)return '<span class="missing-data">시작 미끼 자료 확인 필요</span>';
    return paths.map(p=>`<span class="bait-path">${p.complete?'':'<b class="missing-data">이전 미끼 미확인 · </b>'}${p.steps.map(step=>{
      const f=M.byId.get(step.id);if(!f)return '<span>물고기 '+step.id+'</span>';if(!f.fish){const first=p.steps[1],observed=first?first.routes[0]&&M.biteTime(first.id,first.routes[0]):fish&&M.biteTime(fish.id,route);return '<span class="primary-bait">'+link(tcFish(f),f.name)+(observed?'<small class="primary-bait-samples" title="'+esc(first?'첫 생미끼 물고기 '+M.byId.get(first.id).name:'대상 물고기')+' 입질 시간 표본">입질 표본 '+observed.samples.toLocaleString()+'건</small>':'<small class="primary-bait-samples">입질 표본 미확인</small>')+(window.FishingBaitRankingView?.badge(first?first.routes[0]?.baitChoice:route.baitChoice)||'')+'</span>';}
      const variants=[...new Set((step.routes.length?step.routes:[{}]).map(r=>(['!!','!!!','!'][r.tug]||'입질 미확인')+' · '+(['일반 낚아채기','강력한 낚아채기','섬세한 낚아채기'][r.hookset]||'낚아채기 미확인')+(r.snagging?' · 갈고리 낚시 필요':'')))];
      const time=step.routes[0]&&M.biteTime(step.id,step.routes[0]);return `<span class="detail-mooch">${reference(step.id)}<small>${esc(variants.join(' / '))} · ${time?'약 '+time.min+'–'+time.max+'초':'시간 미확인'}</small></span>`;
    }).join('<span aria-hidden="true"> → </span>')}</span>`).join('<span class="path-or">또는</span>');
  }
  function baitAlternatives(fish,route){
    return M.baitOptions(fish.id,route).map(option=>{
      const a=option.alternative,v=option.versatile;
      const observed=o=>link(tcFish(o.bait),o.bait.name)+' <small>약 '+o.time.min+'–'+o.time.max+'초 · 입질 표본 '+o.samples.toLocaleString()+'건</small>';
      return '<div class="bait-alternatives">'+(option.mooch?'<strong>'+esc(option.fish.name)+' · 시작 미끼 대체</strong>':'')+(a?'<div>대체 미끼 · '+observed(a)+'</div>':'<div class="bait-unconfirmed">대체 미끼 기록 미확인</div>')+'<div class="'+(v||option.versatilePrimary?'bait-versatile':'bait-unconfirmed')+'">'+(option.versatilePrimary?'만능 루어 · 기본 미끼':v?'만능 루어 · 사용 기록 있음 <small>약 '+v.time.min+'–'+v.time.max+'초 · 입질 표본 '+v.samples.toLocaleString()+'건</small>':'만능 루어 · 기록 미확인')+'</div></div>';
    }).join('')+(window.FishingBaitRankingView?.render(M,fish,route)||'');
  }
  function facts(route,fish,compact=false){const tags=[],time=E.timeWindow(route);if(time)tags.push(time);else if(fish.timed)tags.push('시간 조건 확인 필요');else if(compact)tags.push('시간 제한 없음');if(route.weathersFrom?.length)tags.push('이전 날씨: '+route.weathersFrom.map(id=>D.weathers[id]).join(' / '));if(route.weathers?.length)tags.push('현재 날씨: '+route.weathers.map(id=>D.weathers[id]).join(' / '));else if(fish.weathered)tags.push('날씨 조건 확인 필요');else if(compact)tags.push('날씨 제한 없음');if(route.oceanFishingTime)tags.push('먼바다 '+({1:'노을',2:'낮',3:'밤'}[route.oceanFishingTime]||'시간 확인 필요'));
    if(!compact&&route.tug!==undefined)tags.push('입질 '+['!!','!!!','!'][route.tug]);if(!compact&&route.hookset!==undefined)tags.push(['일반 낚아채기','강력한 낚아채기','섬세한 낚아채기'][route.hookset]);if(route.snagging)tags.push('갈고리 낚시 필요');if(route.minGathering>0)tags.push('획득력 '+route.minGathering+' 이상');if(route.aLure>0)tags.push('거대한 루어 '+route.aLure+'회');if(route.mLure>0)tags.push('소박한 루어 '+route.mLure+'회');
    const bite=M.biteTime(fish.id,route);if(bite&&!compact)tags.push(`입질 약 ${bite.min}–${bite.max}초`);
    if(route.shadowSize!==undefined)tags.push('어영 '+['소형','중형','대형'][route.shadowSize]);if(route.speed!==undefined)tags.push('속도 '+['매우 느림','느림','보통','빠름','더 빠름','매우 빠름'][route.speed]);
    return tags.filter(Boolean).map(t=>`<span>${esc(t)}</span>`).join('');
  }
  function routeCard(route,fish,base,compareIndex=null){const p=D.spots[route.spotKey],url=`https://ffxivteamcraft.com/db/ko/${p.kind==='spear'?'spearfishing-spot':'fishing-spot'}/${p.id}`;return `<div class="route"><div class="route-place"><strong>${esc(p.name)}</strong><span>${esc(p.area)}${p.coords?` · X:${p.coords.x} Y:${p.coords.y}`:''}</span>${link(url,'낚시터')}</div>${route.bait?`<div class="route-bait"><div>${baitPaths(route,base,fish)}</div></div>${baitAlternatives(fish,route)}`:''}${!route.verified?'<p class="missing-data">낚시터만 확인된 어종입니다. 미끼·출현 조건 자료 확인이 필요해요.</p>':''}<div class="condition-tags">${facts(route,fish)}</div>${route.predators?.length?`<div class="predator-condition"><strong>${p.kind==='spear'?'숨은 어장 출현 조건':'어부의 직감 조건'}</strong><div>${route.predators.map(f=>`${reference(f.id)} <b>× ${f.amount}</b>`).join(' · ')}</div><p>수집 체크와 별개로, 해당 낚시에서 조건 물고기를 잡아야 합니다.</p></div>`:''}${fish.folklore?`<p>전승록: ${link(tcFish(M.byId.get(fish.folklore)),M.byId.get(fish.folklore).name)}</p>`:''}${route.video?link(route.video,'참고 영상'):''}${compareIndex!==null?(strategy?.render(fish,route,{open:true})||'')+(comparison?.render(route,fish,compareIndex)||''):''}</div>`;}
  function group(g,view,index){const id=+g.key,bait=view==='bait'&&M.byId.get(id);return `<details class="fish-group" ${index===0?'open':''}><summary>${bait?.icon?`<img src="${esc(bait.icon)}" alt="" width="32" height="32" loading="lazy">`:''}<span><strong>${esc(g.name)}</strong>${g.area?`<small>${esc(g.area)}</small>`:''}</span><span class="group-count">${g.entries.length}종</span></summary><div>${g.entries.map(({fish:f,routes})=>`<article class="fish-row"><div class="fish-row-heading"><img src="${esc(f.icon)}" alt="" width="40" height="40" loading="lazy"><button class="row-name" data-fish-detail="${f.id}"><strong>${esc(f.name)}</strong><small>${esc(number(f))}${f.level?' · Lv.'+f.level:''}</small></button><button data-caught="${f.id}" aria-label="${esc(f.name)} 수집" aria-pressed="false">수집 체크</button></div>${routes.length?routes.map(r=>routeCard(r,f,view==='bait'&&g.key!=='unknown'?g.key:null)).join(''):'<p class="missing-data">조건 자료 확인 필요 · 물고기 이름을 눌러 Teamcraft에서 확인해 주세요.</p>'}</article>`).join('')}</div></details>`;}
  function render(){const view=$('view').value,isBook=view==='book';groups=isBook?[]:M.groups(filtered,view,options());const items=isBook?filtered:groups,size=isBook?100:8,totalPages=Math.max(1,Math.ceil(items.length/size));page=Math.min(page,totalPages);const start=(page-1)*size,part=items.slice(start,start+size);pageFish=isBook?part:[...new Map(part.flatMap(g=>g.entries.map(x=>[x.fish.id,x.fish]))).values()];
    $('catalogTitle').textContent=kinds[kind]+(isBook?'':view==='bait'?' · 미끼별':' · 장소별');$('resultCount').textContent=`${filtered.length.toLocaleString()}종`+(!isBook?` · ${groups.length}개 묶음`:filtered.length?` · ${start+1}–${start+part.length}`:'');
    const o=options(),plain=!o.query&&o.status==='all'&&o.region==='all'&&o.bait==='all'&&o.rarity==='all';$('viewHint').textContent=isBook?(plain?'게임 도감 번호순 · 아이콘 = 수집 체크 · 낚시 조건 = 자세히 보기':'검색·필터 결과를 모아 표시합니다. 게임 페이지와 비교하려면 필터를 초기화해 주세요.'):'미끼·장소 이름을 눌러 물고기를 펼칩니다. 여러 경로가 있으면 각 묶음에 표시해요.';
    $('collectionLayoutSwitch').hidden=!isBook;
    $('gridViewport').hidden=!isBook;$('fishGroups').hidden=isBook;$('fishGrid').innerHTML=isBook?part.map(tile).join('')+Array.from({length:part.length?100-part.length:0},()=>'<span class="empty-slot" aria-hidden="true"></span>').join(''):'';$('fishGroups').innerHTML=isBook?'':part.map((g,i)=>group(g,view,i)).join('');$('emptyResults').hidden=!!filtered.length;$('markPage').hidden=!isBook||!part.length;$('markPage').textContent=`이 페이지 ${part.length}종 모두 수집`;
    const nums=[...new Set([1,...Array.from({length:5},(_,i)=>page+i-2).filter(n=>n>0&&n<=totalPages),totalPages])].sort((a,b)=>a-b),nav=`<button data-page="${page-1}" ${page===1?'disabled':''} aria-label="이전 페이지">←</button>`+nums.map((n,i)=>(i&&n-nums[i-1]>1?'<span>…</span>':'')+`<button data-page="${n}" ${n===page?'aria-current="page"':''} aria-label="${n}페이지">${n}</button>`).join('')+`<button data-page="${page+1}" ${page===totalPages?'disabled':''} aria-label="다음 페이지">→</button><span>${page} / ${totalPages} 페이지</span>`;for(const id of ['pagination','paginationTop']){$(id).innerHTML=nav;$(id).hidden=totalPages<=1;}
    counts();updateChecks();
  }
  function detailMarkup(f,titleId){const id=f.id;return `<div class="detail-hero">${f.icon?`<img src="${esc(f.icon)}" alt="" width="64" height="64">`:''}<div><p>${esc(number(f))}${f.level?' · Lv.'+f.level:''}</p><h2 id="${esc(titleId)}">${esc(f.name)}</h2><p lang="en">${esc(f.original)}</p></div></div>${known.has(id)?`<button class="detail-check" data-caught="${id}" aria-pressed="false">수집 체크</button>`:''}<div class="detail-links">${link(tcFish(f),'Teamcraft에서 보기')} ${link('https://guide.ff14.co.kr/lodestone/search?keyword='+encodeURIComponent(f.name),'한국 공식 가이드 검색')}</div><h3>낚시 장소와 조건</h3>${f.routes?.length?f.routes.map((r,i)=>routeCard(r,f,null,i)).join(''):'<p class="missing-data">이 항목의 낚시 조건 자료가 없어요. Teamcraft에서 최신 정보를 확인해 주세요.</p>'}<p class="detail-footnote">출현 시간은 에오르제아 시간(ET), 입질 시간은 실제 초 단위 관측 범위입니다. 입질 통계는 모으기·루어 사용 여부를 구분하지 않습니다. 실시간 날씨·현재 직감 활성 상태는 읽지 않습니다. 대체 미끼는 같은 낚시터의 관측 기록을 기준으로 표시합니다. 관측 건수는 입질 확률이 아니며, 기록 미확인은 사용 불가를 뜻하지 않습니다. 생미끼 경로의 대체품은 시작 미끼에만 적용됩니다.</p>`;}
  function detail(id){const f=M.byId.get(id);if(!f)return;detailId=id;$('detailBody').innerHTML=detailMarkup(f,'detailTitle');updateChecks();if(!$('detailDialog').open)$('detailDialog').showModal();}
  function planDetails(id,route,titleId){
    const fish=M.byId.get(id),spot=D.spots[route.spotKey],index=fish?.routes.indexOf(route);if(!fish||index<0)return '';
    return `<div class="plan-detail-tools"><span id="${esc(titleId)}">${esc(spot.name)}${spot.coords?` · X:${spot.coords.x} Y:${spot.coords.y}`:''}</span><div><button data-fish-detail="${id}" aria-label="${esc(fish.name)} 전체 상세 보기">전체 상세 ↗</button><button data-plan-detail="${id}" aria-label="${esc(fish.name)} 낚시 조건 접기">접기 ×</button></div></div>
      <div class="plan-detail-grid">
        <div class="plan-detail-conditions"><h4>출현 조건</h4><div class="condition-tags">${facts(route,fish,true)}</div>
          ${route.predators?.length?`<div class="plan-detail-intuition"><strong>직감 준비</strong>${route.predators.map(p=>`<span>${reference(p.id)} ×${p.amount}</span>`).join('')}</div>`:''}
          ${fish.folklore?`<p>전승록 · ${link(tcFish(M.byId.get(fish.folklore)),M.byId.get(fish.folklore).name)}</p>`:''}${route.video?link(route.video,'참고 영상'):''}
        </div>
        <div class="plan-detail-baits"><h4>미끼 경로 · 대체품</h4><div class="route-bait"><div>${baitPaths(route,null,fish)}</div></div>${baitAlternatives(fish,route)}</div>
        ${comparison?.render(route,fish,index,0,true)||'<div><h4>같은 입질 비교</h4><p>입질 자료 확인 필요</p></div>'}
      </div>${strategy?.render(fish,route)||''}<p class="plan-detail-note">같은 낚시터 관측 기준 · 시간·날씨·직감에 따라 경쟁 어종이 달라집니다. 기록 미확인은 사용 불가를 뜻하지 않습니다.</p>`;
  }
  window.FishingDetails={renderPlan:planDetails,sync:updateChecks};
  function previewImport(){try{if(!$('importText').value.trim()){$('applyImport').disabled=true;$('importPreview').textContent='';return;}const result=E.parseTransfer($('importText').value,known),fresh=[...result.ids].filter(id=>!caught.has(id)).length;$('applyImport').disabled=!result.ids.size;$('importPreview').textContent=`수집 ID ${result.ids.size}개 · 새로 추가 ${fresh}개`+(result.ignored?` · 현재 도감에 없는 ID ${result.ignored}개 제외`:'');return result;}catch(e){$('applyImport').disabled=true;$('importPreview').textContent=e.message;}}
  async function fileImport(input){const file=input.files[0];if(!file)return;try{if(file.size>2000000)throw Error('2MB 이하 JSON 파일을 선택해 주세요.');$('importText').value=await file.text();previewImport();}catch(e){$('importPreview').textContent=e.message;}finally{input.value='';}}
  function events(){
    $('search').addEventListener('input',refilter);$('search').addEventListener('compositionupdate',()=>queueMicrotask(refilter));$('search').addEventListener('compositionend',refilter);$('clearSearch').addEventListener('click',()=>{$('search').value='';refilter();$('search').focus();});for(const id of ['status','region','bait','rarity'])$(id).addEventListener('change',refilter);$('view').addEventListener('change',()=>{if($('view').value==='bait')$('status').value='missing';refilter();});
    for(const id of ['resetFilters','emptyReset'])$(id).addEventListener('click',reset);for(const type of ['rod','spear'])$(type+'Mode').addEventListener('click',()=>chooseKind(type));$('refreshResults').addEventListener('click',refilter);
    document.addEventListener('click',event=>{const b=event.target.closest('[data-caught],[data-fish-detail],[data-page]');if(!b||b.disabled)return;if(b.hasAttribute('data-caught')){const id=+b.dataset.caught;if(!known.has(id))return;try{const has=!read().has(id);save([[id,has]],`${M.byId.get(id).name} · ${has?'수집했어요.':'수집 체크를 해제했어요.'}`);}catch{notify('기존 기록을 읽지 못해 변경하지 않았어요.');}}else if(b.hasAttribute('data-fish-detail'))detail(+b.dataset.fishDetail);else{page=+b.dataset.page;render();$('catalog').scrollIntoView({block:'start'});$('paginationTop').querySelector('[aria-current]')?.focus({preventScroll:true});}});
    $('markPage').addEventListener('click',()=>save(pageFish.map(f=>[f.id,true]),`현재 페이지 ${pageFish.length}종을 수집으로 체크했어요.`));$('undo').addEventListener('click',()=>{const previous=history.at(-1);if(!previous)return;try{const latest=read();for(const [id,value] of previous){if(value)latest.add(id);else latest.delete(id);}S.write(localStorage,latest);caught=latest;history.pop();counts();updateChecks();if($('status').value!=='all')$('refreshResults').hidden=false;notify('방금 변경을 되돌렸어요.');}catch{notify('기록을 저장하지 못해 되돌리지 않았어요.');}});
    $('closeNotice').addEventListener('click',()=>$('notice').hidden=true);$('closeDetail').addEventListener('click',()=>$('detailDialog').close());$('detailDialog').addEventListener('close',()=>detailId=null);
    $('openRecords').addEventListener('click',()=>{previewImport();$('recordMessage').textContent='';$('recordsDialog').showModal();});$('closeRecords').addEventListener('click',()=>$('recordsDialog').close());$('importText').addEventListener('input',previewImport);$('chooseImport').addEventListener('click',()=>$('importFile').click());$('importFile').addEventListener('change',event=>fileImport(event.target));$('applyImport').addEventListener('click',()=>{const result=previewImport();if(!result?.ids.size)return;try{const latest=read(),added=[...result.ids].filter(id=>!latest.has(id)).length,message=`${added}개 수집 기록을 추가했어요.`;if(merge(result.ids,message)){$('recordMessage').textContent=message;$('importText').value='';previewImport();}}catch{notify('기존 기록을 읽을 수 없어 가져오지 않았어요.');}});
    $('exportRecords').addEventListener('click',()=>{try{const blob=new Blob([E.backup(read())],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ffxiv-fishing-log-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{$('recordMessage').textContent='기록을 읽을 수 없어 내보내지 못했어요.';}});
    $('copyTeamcraft').addEventListener('click',async()=>{let text;try{text=E.teamcraft(read(),known);}catch{$('recordMessage').textContent='기록을 읽을 수 없어 복사하지 못했어요.';return;}try{await navigator.clipboard.writeText(text);$('recordMessage').textContent='Teamcraft용 기록을 복사했어요.';$('copyFallbackLabel').hidden=true;}catch{$('copyFallbackLabel').hidden=false;$('copyFallback').value=text;$('copyFallback').focus();$('copyFallback').select();$('recordMessage').textContent='아래 텍스트를 직접 복사해 주세요.';}});
    window.addEventListener('storage',event=>{if(!S.isStorageKey(event.key))return;try{caught=read();history=[];counts();updateChecks();previewImport();if($('status').value!=='all')$('refreshResults').hidden=false;notify('연동된 수집 기록을 반영했어요.');}catch{notify('다른 탭의 기록을 읽지 못했어요.');}});
    window.addEventListener('pageshow',()=>{try{caught=read();counts();updateChecks();previewImport();if($('status').value!=='all')$('refreshResults').hidden=false;}catch{notify('연동 기록을 읽지 못했어요. 기존 기록은 보존됩니다.');}});
    document.addEventListener('error',event=>{const img=event.target;if(!(img instanceof HTMLImageElement))return;const fallback=document.createElement('span');fallback.className='image-fallback';fallback.setAttribute('aria-hidden','true');fallback.textContent='어';img.replaceWith(fallback);},true);
  }
  try{if(!D||!E||!S||D.count!==D.fishes.length)throw Error('도감 자료를 불러오지 못했어요. 새로고침해 주세요.');M=E.create(D,window.FISHING_BITE_TIMES);comparison=window.FishingComparison?.mount({model:M,reference});strategy=window.FishingStrategyView?.create(D,M,window.FISHING_STRATEGIES,window.FISHING_BAIT_CATCHES);try{caught=read();}catch{$('fatal').textContent='저장된 기록을 읽지 못했어요. 기존 기록은 덮어쓰지 않았습니다.';$('fatal').hidden=false;}
    const baits=[...new Set(D.fishes.filter(f=>f.kind==='rod').flatMap(f=>f.routes.flatMap(r=>M.paths(r).filter(p=>p.complete).map(p=>p.ids[0]))))].map(id=>M.byId.get(id)).sort((a,b)=>a.name.localeCompare(b.name,'ko'));$('bait').insertAdjacentHTML('beforeend',baits.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')+'<option value="unknown">시작 미끼 확인 필요</option>');
    fillRegions();events();refilter();$('dataNote').textContent=`${D.updatedAt} 공개 데이터 기준 · 어류 ${D.counts.rod.toLocaleString()}종 · 작살 ${D.counts.spear.toLocaleString()}종 · 낚시 조건 자료 확인 필요 ${D.missingConditions.length}종.`;
    window.FishingScanUI?.mount({fishes:D.fishes,apply:ids=>{if(!Array.isArray(ids)||!ids.length||ids.some(id=>!known.has(id)))return {ok:false,error:'도감에 없는 물고기가 포함되어 있어요.'};try{const latest=read(),fresh=[...new Set(ids)].filter(id=>!latest.has(id)).length,message=`캡처에서 ${fresh}종 수집 기록을 추가했어요.`;if(!merge(new Set(ids),message))return {ok:false,error:'저장하지 못해 적용하지 않았어요.'};$('recordMessage').textContent=message;return {ok:true,message};}catch{return {ok:false,error:'기존 기록을 읽지 못했어요.'};}}});
    $('appContent').hidden=false;$('loading').hidden=true;$('openRecords').disabled=false;
    window.FishingPlanner?.mount({data:D,model:M,getCaught:()=>new Set(caught)});
  }catch(e){$('loading').hidden=true;$('fatal').textContent=e.message;$('fatal').hidden=false;}
})();
