(function(){
  'use strict';
  window.FishingScanUI={mount({fishes,apply}){
    const S=window.FishingScanner,$=id=>document.getElementById(id),pages=S.pagesFor(fishes),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    $('scanDialog').innerHTML=`<div class="dialog-top"><h2 id="scanTitle">도감 캡처로 등록</h2><button id="closeScan" aria-label="캡처 등록 닫기">닫기 ×</button></div><p class="scan-intro">검색·필터를 해제한 10열 × 10행 도감 캡처를 추가하세요. 도감 종류와 페이지 번호는 직접 선택합니다. 이미지는 이 브라우저에서만 처리해요.</p><div class="scan-upload"><button id="scanAddImages">캡처 이미지 추가</button><input id="scanFiles" type="file" multiple accept="image/png,image/jpeg,image/webp,image/bmp" hidden><span>이 창에서 Ctrl+V로 붙여넣기 · 최대 20장</span></div><p id="scanStatus" role="status" aria-live="polite">캡처를 추가하면 물음표 아이콘을 읽습니다.</p><div id="scanFileList" class="scan-file-list" aria-label="추가한 캡처"></div><section id="scanWorkspace" hidden><div class="scan-controls"><label for="scanPage">도감 종류 · 게임 페이지<select id="scanPage"><option value="">종류와 페이지 선택</option>${pages.map(p=>`<option value="${p.key}">${p.label} · ${p.items[0].order}–${p.items.at(-1).order}</option>`).join('')}</select></label><button id="scanRemove" class="quiet">이 캡처 삭제</button></div><p id="scanPageHelp"></p><div class="scan-layout"><div class="scan-preview"><div class="scan-scroll"><div class="scan-stage"><canvas id="scanCanvas" aria-label="도감 캡처의 10열 10행 영역"></canvas><div id="scanOverlay" class="scan-overlay"></div></div></div><p id="scanCropHelp"></p><div class="scan-crop-actions"><button id="scanEditCrop">아이콘 영역 조정</button><button id="scanFullImage" hidden>이미지 전체</button><button id="scanAnalyze">다시 인식</button></div></div><section id="scanCellTools" class="scan-cell-tools" aria-labelledby="scanCellTitle" hidden><h3 id="scanCellTitle"></h3><div class="scan-cell-actions"><button id="scanLearned" aria-pressed="false">수집으로 표시</button><button id="scanMissing" aria-pressed="false">미수집으로 표시</button><button id="scanNextReview">다음 확인 필요 칸</button></div><p>이미지 위 표시: ✓ 수집 · − 미수집 · ! 확인 필요. 칸을 누르면 상태가 바뀝니다.</p></section></div><label class="scan-reviewed"><input id="scanReviewed" type="checkbox"> 이 캡처의 도감 종류·페이지 번호와 수집 상태를 확인했어요.</label></section><div class="scan-apply"><strong id="scanTotal"></strong><p id="scanReadyNote"></p><button id="scanApply" class="primary" disabled>수집 기록에 추가</button><p>수집한 물고기만 기존 기록에 추가해요. 미수집 칸이나 캡처에 없는 물고기의 기록은 바꾸지 않습니다.</p></div>`;
    const canvas=$('scanCanvas'),ctx=canvas.getContext('2d'),labels={learned:'수집',missing:'미수집',review:'확인 필요'};
    let entries=[],selected=0,cell=0,bitmap=null,busy=false,editing=false,version=0,drag=null;
    const current=()=>entries[selected],pageFor=e=>pages.find(p=>p.key===e?.page),status=text=>$('scanStatus').textContent=text,visibleResults=e=>(e?.results||[]).slice(0,pageFor(e)?.items.length||100);
    function draw(){const e=current();if(!e||!bitmap)return;canvas.width=bitmap.width;canvas.height=bitmap.height;ctx.drawImage(bitmap,0,0);if(!editing)return;const r=e.crop;ctx.fillStyle='#03081488';ctx.fillRect(0,0,canvas.width,r.y*canvas.height);ctx.fillRect(0,(r.y+r.h)*canvas.height,canvas.width,(1-r.y-r.h)*canvas.height);ctx.strokeStyle='#9bd9d3';ctx.lineWidth=Math.max(1,canvas.width/600);for(let i=0;i<=10;i++){ctx.beginPath();ctx.moveTo((r.x+r.w*i/10)*canvas.width,r.y*canvas.height);ctx.lineTo((r.x+r.w*i/10)*canvas.width,(r.y+r.h)*canvas.height);ctx.stroke();ctx.beginPath();ctx.moveTo(r.x*canvas.width,(r.y+r.h*i/10)*canvas.height);ctx.lineTo((r.x+r.w)*canvas.width,(r.y+r.h*i/10)*canvas.height);ctx.stroke();}}
    function render(){const e=current(),p=pageFor(e),results=visibleResults(e),all=entries.flatMap(visibleResults);let ids;
      try{if(!busy&&!editing)ids=S.prepareImport(entries,fishes);$('scanReadyNote').textContent='';}catch(error){$('scanReadyNote').textContent=entries.length?error.message:'';}
      $('scanWorkspace').hidden=!e;$('scanFileList').innerHTML=entries.map((entry,i)=>`<button data-scan-file="${i}" aria-pressed="${i===selected}" ${busy?'disabled':''}>${i+1}. ${esc(entry.file.name)}<span>${pageFor(entry)?.label||'페이지 미지정'} · ${entry.reviewed?'✓ 확인 완료':entry.results?'검토 중':'인식 전'}</span></button>`).join('');
      $('scanTotal').textContent=`캡처 ${entries.length}장 · 수집 ${all.filter(r=>r.state==='learned').length}칸 · 미수집 ${all.filter(r=>r.state==='missing').length}칸 · 확인 필요 ${all.filter(r=>r.state==='review').length}칸`;$('scanApply').disabled=!ids;$('scanApply').textContent=ids?`${ids.length}종 수집 기록에 추가`:'수집 기록에 추가';for(const id of ['scanAddImages','scanFiles'])$(id).disabled=busy;if(!e)return;
      $('scanPage').value=e.page||'';$('scanPageHelp').textContent=p?`${p.label} · ${p.items[0].name}부터 ${p.items.at(-1).name}까지 ${p.items.length}종${p.items.length<100?' · 남은 빈 칸은 제외합니다.':''}`:'게임 화면의 도감 종류와 페이지 번호를 선택해 주세요.';
      $('scanReviewed').checked=!!e.reviewed;$('scanReviewed').disabled=busy||editing||!p||!e.results||results.some(r=>r.state==='review');
      $('scanOverlay').hidden=editing||!e.results;if(e.crop){$('scanOverlay').style.inset=`${e.crop.y*100}% auto auto ${e.crop.x*100}%`;$('scanOverlay').style.width=e.crop.w*100+'%';$('scanOverlay').style.height=e.crop.h*100+'%';}
      $('scanOverlay').innerHTML=e.results?Array.from({length:100},(_,i)=>{const r=results[i],f=p?.items[i];if(!r)return '<span class="scan-unused" aria-label="도감의 빈 칸"></span>';const name=f?`${f.order}. ${f.name}`:`${Math.floor(i/10)+1}행 ${i%10+1}열`;return `<button class="scan-cell ${r.state} ${cell===i?'selected':''}" data-scan-cell="${i}" aria-label="${esc(name)} ${labels[r.state]} · 누르면 변경" ${busy?'disabled':''}><b>${r.state==='learned'?'✓':r.state==='missing'?'−':'!'}</b><span>${f?.order||i+1}</span></button>`;}).join(''):'';
      const r=results[cell],f=p?.items[cell];$('scanCellTools').hidden=editing||!r;$('scanCellTitle').textContent=r?`${f?f.order+'. '+f.name:(Math.floor(cell/10)+1)+'행 '+(cell%10+1)+'열'} · ${labels[r.state]}`:'';for(const state of ['learned','missing']){const b=$(state==='learned'?'scanLearned':'scanMissing');b.disabled=busy||!r;b.setAttribute('aria-pressed',String(r?.state===state));}$('scanNextReview').disabled=busy||!results.some(r=>r.state==='review');
      for(const id of ['scanPage','scanRemove'])$(id).disabled=busy;for(const id of ['scanAnalyze','scanEditCrop','scanFullImage'])$(id).disabled=busy||!bitmap;$('scanFullImage').hidden=!editing;$('scanEditCrop').textContent=editing?'영역 조정 중':'아이콘 영역 조정';$('scanCropHelp').textContent=editing?'상단 페이지 번호를 제외한 10열 × 10행 칸 전체를 드래그하세요. 마지막 페이지의 빈 칸도 포함합니다.':'선택 칸의 빛나는 테두리는 판정 중심에서 제외합니다. 이미지 위 ✓ / − / ! 표시를 확인해 주세요.';draw();
    }
    function imagePixels(){const c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;const context=c.getContext('2d',{willReadFrequently:true});context.drawImage(bitmap,0,0);return context.getImageData(0,0,c.width,c.height);}
    async function analyze(){const e=current();if(!e||!bitmap||busy)return;const error=S.validateRect(e.crop,bitmap.width,bitmap.height);if(error){status(error);return;}const token=++version;busy=true;e.reviewed=false;e.results=null;render();status('10 × 10 아이콘에서 수집 상태를 읽고 있어요.');try{const results=await S.analyze(imagePixels(),e.crop,{cancelled:()=>version!==token});if(token!==version)return;e.results=results;editing=false;cell=Math.max(0,visibleResults(e).findIndex(r=>r.state==='review'));status('인식했어요. 도감 종류·페이지와 이미지 위 상태를 확인해 주세요.');}catch(error){if(token===version)status(error.message);}finally{if(token===version){busy=false;render();}}}
    async function select(index){const token=++version;selected=index;cell=0;busy=true;editing=false;bitmap?.close();bitmap=null;render();try{let image=await createImageBitmap(current().file);if(image.width<200||image.height<200||image.width*image.height>32000000){image.close();throw Error('200×200 이상, 3,200만 화소 이하 캡처를 사용해 주세요.');}if(token!==version){image.close();return;}if(Math.max(image.width,image.height)>2000){const scale=2000/Math.max(image.width,image.height),smaller=await createImageBitmap(image,{resizeWidth:Math.round(image.width*scale),resizeHeight:Math.round(image.height*scale)});image.close();image=smaller;}if(token!==version){image.close();return;}bitmap=image;current().crop||=S.defaultCrop(image.width,image.height);busy=false;render();if(!current().results)await analyze();else status('선택한 캡처를 확인해 주세요.');}catch(error){if(token===version){busy=false;status(error.message);render();}}}
    async function add(files){if(busy)return;const chosen=Array.from(files).filter(f=>/^image\/(png|jpeg|webp|bmp)$/.test(f.type));if(!chosen.length){status('PNG·JPG·WebP·BMP 이미지를 선택해 주세요.');return;}if(entries.length+chosen.length>20||chosen.some(f=>f.size>12000000)){status('한 번에 20장 이하, 파일당 12MB 이하로 추가해 주세요.');return;}const first=entries.length;entries.push(...chosen.map(file=>({file,page:'',reviewed:false,results:null})));await select(first);}
    function setState(state){const e=current(),r=visibleResults(e)[cell];if(!r||busy||editing)return;r.state=state;r.manual=true;e.reviewed=false;render();}
    function changeCrop(rect){if(!current()||busy)return;current().crop=rect;current().results=null;current().reviewed=false;editing=true;render();}
    const point=event=>{const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(event.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(event.clientY-r.top)/r.height))};};
    canvas.addEventListener('pointerdown',event=>{if(!editing||busy||!bitmap)return;drag={start:point(event),before:{...current().crop}};canvas.setPointerCapture(event.pointerId);});canvas.addEventListener('pointermove',event=>{if(!drag)return;const p=point(event),s=drag.start;current().crop={x:Math.min(p.x,s.x),y:Math.min(p.y,s.y),w:Math.abs(p.x-s.x),h:Math.abs(p.y-s.y)};draw();});canvas.addEventListener('pointerup',()=>{if(!drag)return;const r=current().crop;if(r.w<.03||r.h<.03)current().crop=drag.before;else changeCrop(r);drag=null;draw();});canvas.addEventListener('pointercancel',()=>{if(drag){current().crop=drag.before;drag=null;draw();}});
    $('openScan').disabled=false;$('openScan').addEventListener('click',()=>{$('scanDialog').showModal();if(entries.length)select(selected);else render();});$('closeScan').addEventListener('click',()=>$('scanDialog').close());$('scanDialog').addEventListener('close',()=>{++version;busy=false;if(drag&&current())current().crop=drag.before;drag=null;bitmap?.close();bitmap=null;render();});
    $('scanAddImages').addEventListener('click',()=>$('scanFiles').click());$('scanFiles').addEventListener('change',event=>{add(event.target.files);event.target.value='';});document.addEventListener('paste',event=>{if(!$('scanDialog').open)return;const files=[...(event.clipboardData?.items||[])].filter(i=>i.kind==='file'&&i.type.startsWith('image/')).map(i=>i.getAsFile()).filter(Boolean);if(files.length){event.preventDefault();add(files);}});
    $('scanFileList').addEventListener('click',event=>{const b=event.target.closest('[data-scan-file]');if(b&&!busy)select(+b.dataset.scanFile);});$('scanPage').addEventListener('change',event=>{if(!current()||busy)return;current().page=event.target.value;current().reviewed=false;cell=Math.min(cell,(pageFor(current())?.items.length||100)-1);render();});$('scanOverlay').addEventListener('click',event=>{const b=event.target.closest('[data-scan-cell]');if(!b||busy||editing)return;cell=+b.dataset.scanCell;setState(current().results[cell].state==='learned'?'missing':'learned');});$('scanLearned').addEventListener('click',()=>setState('learned'));$('scanMissing').addEventListener('click',()=>setState('missing'));$('scanNextReview').addEventListener('click',()=>{const rows=visibleResults(current()),after=rows.findIndex((r,i)=>i>cell&&r.state==='review');cell=after>=0?after:Math.max(0,rows.findIndex(r=>r.state==='review'));render();});$('scanReviewed').addEventListener('change',event=>{if(current())current().reviewed=event.target.checked;render();});
    $('scanEditCrop').addEventListener('click',()=>{if(!current()||busy)return;editing=true;current().reviewed=false;render();});$('scanFullImage').addEventListener('click',()=>changeCrop({x:0,y:0,w:1,h:1}));$('scanAnalyze').addEventListener('click',analyze);$('scanRemove').addEventListener('click',()=>{if(busy||!current())return;entries.splice(selected,1);bitmap?.close();bitmap=null;if(entries.length)select(Math.min(selected,entries.length-1));else{selected=0;editing=false;status('캡처를 추가해 주세요.');render();}});
    $('scanApply').addEventListener('click',()=>{try{const ids=S.prepareImport(entries,fishes),result=apply(ids);if(!result?.ok){status(result?.error||'수집 기록을 저장하지 못했어요.');return;}$('scanDialog').close();}catch(error){status(error.message);}});render();
  }};
})();
