const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('../../ocean-fishing/node_modules/jsdom');
test('main page and small window update first-hand analysis from input', async () => {
  const root = path.resolve(__dirname, '..');
  const dom = new JSDOM(fs.readFileSync(path.join(root, 'index.html'), 'utf8'), { url: 'http://localhost/ffxiv/mahjong-helper/', runScripts: 'outside-only' });
  const w = dom.window;
  w.fetch = async () => ({ ok: true, json: async () => JSON.parse(fs.readFileSync(path.join(root, 'yaku-catalog.json'))) });
  for (const script of ['core.js', 'opening-analysis.js', 'partial-dictionary.js', 'quick-input.js', 'meld-input.js', 'unavailable-input.js']) w.eval(fs.readFileSync(path.join(root, script), 'utf8'));
  await w.eval(fs.readFileSync(path.join(root, 'dictionary-app.js'), 'utf8'));
  const input = w.document.getElementById('quickCompact');
  input.value = '23m55567p114889s'; input.dispatchEvent(new w.Event('input', { bubbles: true }));
  const guide = w.document.getElementById('openingGuide');
  assert.match(guide.textContent, /3\.0%/);
  assert.match(guide.textContent, /123장/);
  assert.match(guide.querySelector('.opening-path').textContent, /이페코/);
  input.value = '123m123p123s55z67s9m'; input.dispatchEvent(new w.Event('input', { bubbles: true }));
  assert.match(guide.textContent, /9만을 버린 뒤/);
  assert.equal(guide.querySelector('.opening-best td').textContent, '9만');
  const child = new JSDOM('<body></body>', { url: w.location.href });
  child.window.focus = () => {};
  w.open = () => child.window;
  w.document.getElementById('openPip').click();
  await new Promise(resolve => setTimeout(resolve, 20));
  assert.match(child.window.document.getElementById('pipOpeningGuide').textContent, /9만을 버린 뒤/);
  const pipInput = child.window.document.getElementById('pipQuickCompact');
  pipInput.value = '23m55567p114889s'; pipInput.dispatchEvent(new child.window.Event('input', { bubbles: true }));
  assert.match(child.window.document.getElementById('pipOpeningGuide').textContent, /3\.0%/);
  assert.match(guide.textContent, /123장/);
  w.document.getElementById('clear').click();
  assert.equal(guide.querySelectorAll('.opening-path').length, 0);
  child.window.close(); w.close();
});
