const fs=require('node:fs'),path=require('node:path');
const skills=require('./content.cjs'),official=require('./official.json'),navigation=require('../tools/site-navigation.cjs');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories={mooch:'월척·생미끼',basic:'기본·입질 조절',target:'어종 저격',multiple:'직감·다수 낚시',support:'GP·보조'};
const descriptions={mooch:'월척 준비, 생미끼 프록 유지와 연속 생미끼',basic:'낚시 취소와 입질 대기 시간 조절',target:'원하는 어종을 유인하고 방해 어종 제외',multiple:'직감 조건과 필요한 마릿수 채우기',support:'GP 관리, 소장품과 특수 낚시 조건'};
const source='https://guide.ff14.co.kr/job/Fisher/31?type=L';
const footer=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8').match(/<footer[\s\S]*?<\/footer>/)[0].replaceAll('href="./','href="../').replaceAll('href="fonts/','href="../fonts/');
function renderCard(s){
  const items=s.skills.map(name=>{const item=official.find(o=>o.name===name);if(!item)throw Error('Official skill missing: '+name);return item;});
  return `<article id="${s.id}" class="skill-card${s.id==='makeshift'?' featured':''}" data-category="${s.category}">
    <div class="skill-heading"><div>${s.tag?`<div class="skill-label"><span>${esc(s.tag)}</span></div>`:''}<h3>${esc(s.title)}</h3><p class="skill-meta">${esc(s.meta)}</p></div><a class="permalink" href="#${s.id}" aria-label="${esc(s.title)} 바로가기">#</a></div>
    <ul class="skill-unlocks" aria-label="스킬별 해금 레벨">${items.map(o=>`<li data-skill="${esc(o.name)}"><a class="skill-unlock" href="${source}#${o.anchor}" target="_blank" rel="noopener noreferrer" aria-label="${esc(o.name)} 해금 레벨 ${o.level} · 공식 설명"><img src="${o.icon}" alt="" width="28" height="28" loading="lazy"><span>${esc(o.name)}</span><strong>Lv.${o.level}</strong></a>${o.quest?`<a class="skill-quest" href="${esc(o.quest.url)}" target="_blank" rel="noopener noreferrer">${esc(o.quest.label)} 필요 ↗</a>`:''}</li>`).join('')}</ul>
    <p class="skill-lead">${esc(s.lead)}</p><div class="skill-explanation"><div>${[s.body,...(s.paragraphs||[])].map(p=>`<p>${esc(p)}</p>`).join('')}<p class="skill-note">${esc(s.note)}</p></div><div class="skill-example"><h4>${esc(s.exampleTitle||'사용 예시')}</h4>${s.steps?`<ol class="skill-steps">${s.steps.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>`:`<p>${esc(s.example)}</p>`}${s.exampleTable?`<table class="skill-timing-table"><caption>${esc(s.exampleTable.caption)}</caption><thead><tr>${s.exampleTable.headers.map(t=>`<th scope="col">${esc(t)}</th>`).join('')}</tr></thead><tbody>${s.exampleTable.rows.map(row=>`<tr>${row.map((t,i)=>i?`<td>${esc(t)}</td>`:`<th scope="row">${esc(t)}</th>`).join('')}</tr>`).join('')}</tbody></table>`:''}${s.extra?`<p class="skill-extra">${esc(s.extra)}</p>`:''}</div></div>
${s.research?`<div class="skill-research"><p>${esc(s.research.note)}</p><div>${s.research.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ↗</a>`).join('')}</div></div>`:''}
    <div class="skill-bottom"><div class="related-skills"><span>함께 보기</span>${s.links.map(id=>`<a href="#${id}" data-related>${esc(skills.find(x=>x.id===id).skills[0])}</a>`).join('')}</div><div class="official-links">${items.map(o=>`<a href="${source}#${o.anchor}" target="_blank" rel="noopener noreferrer">${items.length>1?esc(o.name)+' ':''}공식 설명 ↗</a>`).join('')}</div></div>
  </article>`;
}
const cards=Object.entries(categories).map(([id,title],index)=>{const members=skills.filter(s=>s.category===id);return `<section class="skill-group" data-skill-group="${id}" aria-labelledby="group-${id}"><header class="skill-group-heading"><span class="group-number" aria-hidden="true">${String(index+1).padStart(2,'0')}</span><div><h2 id="group-${id}">${title}</h2><p>${descriptions[id]}</p></div><span class="group-count">${members.length}개 설명</span></header><div class="skill-group-cards">${members.map(renderCard).join('\n')}</div></section>`;}).join('\n');
const html=`<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>어부 스킬 안내 · 파판14 도구함</title><meta name="description" content="숙련 낚시꾼으로 생미끼 프록 유지하기, 쿠얼·홍룡 저글링, 인내·교환 방생·루어·직감용 스킬의 사용 순서와 실전 예시."><meta name="theme-color" content="#0b1220"><meta property="og:title" content="어부 스킬 안내"><meta property="og:description" content="생미끼·저격 낚시·직감 준비에 필요한 기술과 사용 순서"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:url" content="https://teo-park.github.io/ffxiv/fisher-skills/"><link rel="canonical" href="https://teo-park.github.io/ffxiv/fisher-skills/"><link rel="icon" href="../favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="../theme.css?v=20260909-line1"><link rel="stylesheet" href="./styles.css?v=20260910-lures1"><script defer src="./app.js?v=20260910-groups2"></script>${navigation.assets('fisher-skills/')}</head>
<body><a class="skip-link" href="#skillList">스킬 설명으로 바로가기</a>${navigation.header('fisher-skills/')}
<main class="skills-main"><div class="skills-masthead"><div><p class="eyebrow">낚시 가이드</p><h1>어부 스킬 안내</h1><p>기술의 효과와 사용 순서, 생미끼·터주 낚시 실전 예시.</p></div><a class="planner-link" href="../fishing-log/">세계를 누비는 어부 ↗</a></div>
<nav class="quick-links" aria-label="어부 가이드"><a href="./" aria-current="page">어부 스킬 안내</a><a href="./big-fish/">터주 유형별 공략 ↗</a></nav>
<nav class="quick-links" aria-label="자주 찾는 스킬"><a href="#makeshift" data-related>생미끼 프록 유지</a><a href="#patience" data-related>인내 중 낚아채기</a><a href="#lures" data-related>루어·재추첨</a><a href="#slap" data-related>교환 방생으로 저격</a></nav>
<section class="skill-controls" aria-label="스킬 찾기" hidden><label for="skillSearch">스킬·상황 검색</label><div class="skill-search"><input type="search" id="skillSearch" autocomplete="off" placeholder="숙련, ㅅㅁㄲ, 쿠얼, 직감, GP…" aria-controls="skillList"><button type="button" id="clearSearch">지우기</button></div><div class="skill-categories" role="group" aria-label="낚시 목적"><button type="button" data-filter="all" aria-pressed="true">전체</button>${Object.entries(categories).map(([id,title])=>`<button type="button" data-filter="${id}" aria-pressed="false">${title}</button>`).join('')}</div></section>
<div class="skill-results-heading"><p id="skillCount" role="status">${skills.length}개 설명 · 낚싯대 낚시 중심</p><span>무료·비영리</span></div><div id="skillList">${cards}</div><p id="noSkills" class="empty-state" hidden>맞는 설명이 없습니다. 검색어나 목적을 바꿔 보세요.</p>
<section class="guide-sources" id="sources"><h2>설명 기준과 출처</h2><p>사이트 운영자가 정리한 어부 스킬 자료를 바탕으로 실전 예시를 구성했습니다. 기술의 이름·레벨·소모 자원과 효과는 <a href="${source}" target="_blank" rel="noopener noreferrer">한국 공식 어부 가이드 ↗</a>를 확인했습니다. 공식 페이지의 안내 기준은 패치 7.0, 확인일은 2026년 9월 10일입니다. 게임 내 최신 툴팁과 차이가 있으면 게임 설명을 우선하세요.</p><p>가상의 A·B 예시는 원리를 설명하기 위한 것입니다. 입질 시간은 관측값이며 어종·미끼·사용 기술에 따라 달라질 수 있습니다. 쿠얼·홍룡의 낚시 조건은 <a href="https://ffxivteamcraft.com/db/ko/item/24993" target="_blank" rel="noopener noreferrer">Teamcraft 홍룡 정보 ↗</a>에서도 확인할 수 있습니다.</p><a href="./README.md">자료 구성·갱신 안내</a></section></main>${footer}</body></html>`;
fs.writeFileSync(path.join(__dirname,'index.html'),html);
console.log(`Built ${skills.length} fishing skill explanations (${new Set(skills.flatMap(s=>s.skills)).size} skills/traits).`);
