// Node.js 20+. Retain only public names, levels, categories and official links.
import { mkdir, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
const base = 'https://guide.ff14.co.kr';
const root = new URL('../', import.meta.url);
export function decode(value) {
  return value.replace(/<[^>]*>/g, '').replace(/&#(x[0-9a-f]+|\d+);/gi, (_, n) => String.fromCodePoint(n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):+n))
    .replace(/&nbsp;/g,' ').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&gt;/g,'>').replace(/&lt;/g,'<').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
}
export function parsePage(html) {
  const body=html.split('<ul class="list_type">')[1]?.split('<div class="pagination">')[0];
  if(!body)throw new Error('Official duty list markup changed');
  return [...body.matchAll(/<a href="\/lodestone\/db\/duty\/([a-f0-9]+)"[^>]*>([\s\S]*?)<\/a>/g)].map(([,id,row])=>{
    const title=row.match(/<cite class="name">([\s\S]*?)<\/cite>/)?.[1];
    const type=row.match(/<em class="type">([\s\S]*?)<\/em>/)?.[1];
    const fields=[...row.matchAll(/<dd>([\s\S]*?)<\/dd>/g)].map(m=>decode(m[1]));
    if(!title||!type||!/^\d+$/.test(fields[0]))throw new Error(`Unexpected duty row: ${id}`);
    const [category,expansion='']=decode(type).split(' > ');
    return {id,name:decode(title.replace(/<i\b[^>]*>[\s\S]*?<\/i>/g,'')),category,expansion,level:+fields[0],itemLevel:/^\d+$/.test(fields[1])?+fields[1]:null};
  });
}
async function get(path) {
  for(let attempt=0;attempt<3;attempt++) {
    try {
      const response=await fetch(base+path,{signal:AbortSignal.timeout(30000)});
      if(!response.ok)throw new Error(`HTTP ${response.status}: ${path}`);
      return await response.text();
    } catch(error) { if(attempt===2)throw error; }
  }
}
export async function update() {
  const index=await get('/lodestone/db/duty');
  const categories=[...index.matchAll(/fnOpenLeftMenu\(3,\s*(\d+),\s*100,[^']*'([^']+)'\)">([^<]+)</g)].map(m=>({id:+m[1],path:decode(m[2]),name:decode(m[3])}));
  if(categories.length<7||new Set(categories.map(c=>c.id)).size!==categories.length)throw new Error('Review official categories before updating');
  const duties=[],ids=new Set();
  for(const category of categories) {
    let count=0;
    for(let page=1;page<=100;page++) {
      const html=await get(category.path+`&page=${page}`);
      const rows=parsePage(html);
      if(!rows.length)throw new Error(`Empty page: ${category.name}/${page}`);
      for(const duty of rows) {
        if(ids.has(duty.id)||duty.category!==category.name)throw new Error(`Duplicate or incorrect category: ${duty.id}`);
        ids.add(duty.id);duties.push(duty);count++;
      }
      const pages=[...html.matchAll(/href="\/lodestone\/db\/duty\?[^"\s]*?page=(\d+)"/g)].map(m=>+m[1]);
      if(!pages.some(p=>p>page))break;
      if(page===100)throw new Error('Pagination overflow');
    }
    category.count=count;console.log(`${category.name}: ${count}`);
  }
  if(duties.length<300)throw new Error('Incomplete duty catalog');
  const data={schemaVersion:1,fetchedAt:new Date().toISOString().slice(0,10),source:base+'/lodestone/db/duty',categories:categories.map(({name,count})=>({name,count})),duties};
  await mkdir(root,{recursive:true});
  await writeFile(new URL('data.js',root),'// Generated by scripts/update-data.mjs from the Korean official guide.\nwindow.DUTY_DATA = '+JSON.stringify(data,null,2)+';\n');
  console.log(`Saved ${duties.length} duties.`);
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)await update();
