import { readFile, writeFile, rename } from 'node:fs/promises';
import assert from 'node:assert/strict';
const root = new URL('../', import.meta.url);
const raw = JSON.parse(await readFile(new URL('.cache/raw-data.json', root), 'utf8'));
// Explicit expansion membership: stop rather than silently assigning a new official category.
const expansions = [
  { id:'arr', name:'신생 에오르제아', version:'2.x', groups:[1,2] },
  { id:'hw', name:'창천의 이슈가르드', version:'3.x', groups:[3,4,5] },
  { id:'sb', name:'홍련의 해방자', version:'4.x', groups:[6,7] },
  { id:'shb', name:'칠흑의 반역자', version:'5.x', groups:[8,9,10] },
  { id:'ew', name:'효월의 종언', version:'6.x', groups:[11,12] },
  { id:'dt', name:'황금의 유산', version:'7.x', groups:[13,14,15] },
];
const cityNames = {gridania:'그리다니아',limsa:'림사 로민사',uldah:'울다하'};
const groups = raw.groups.map(g => {
  const expansion = expansions.find(e => e.groups.includes(g.id));
  assert(expansion, `Map new official category ${g.id} before publishing`);
  return {...g, expansion:expansion.id};
});
// The eight class-specific introductory quests represent one quest per starting city.
const aliases = new Map(), unique = new Map(), quests = [];
for (const source of raw.quests) {
  const key = source.initialClass ? `${source.group}:${source.name}:${source.region}` : source.id;
  if (unique.has(key)) { aliases.set(source.id, unique.get(key)); continue; }
  unique.set(key,source.id);
  const { initialClass, ...quest } = source;
  quests.push({...quest, expansion:groups.find(g=>g.id===quest.group).expansion});
}
const map = new Map(quests.map(q=>[q.id,q]));
for(const q of quests) q.previous = [...new Set(q.previous.map(id=>aliases.get(id)||id).filter(id=>map.has(id)))];
const roots = quests.filter(q=>q.previous.length===0);
assert.equal(roots.length,3,'Unexpected disconnected major-quest chain');
assert(roots.every(q=>q.name==='모험가를 위한 안내'));
const citySeeds = new Map(roots.map(q=>[q.id,Object.keys(cityNames).find(city=>cityNames[city]===q.region)]));
const companySeeds = new Map(['쌍사당','흑와단','불멸대'].map(company=>{
  const q=quests.find(q=>q.name===`내가 가야 할 길(${company})`);
  assert(q,`Missing company fork: ${company}`);
  return [q.id,company];
}));
function inheritedTags(seeds) {
  const memo=new Map(), visiting=new Set();
  function tags(id) {
    if(memo.has(id)) return memo.get(id);
    assert(!visiting.has(id),`Cycle at ${id}`);
    visiting.add(id);
    const value=seeds.has(id)?[seeds.get(id)]:[...new Set(map.get(id).previous.flatMap(tags))];
    assert(!value.includes(undefined),'Unknown route seed');
    visiting.delete(id); memo.set(id,value); return value;
  }
  return tags;
}
const cities=inheritedTags(citySeeds), companies=inheritedTags(companySeeds);
for(const q of quests) {
  q.cities=cities(q.id);
  const tags=companies(q.id);
  q.companies=tags.length===0?['쌍사당','흑와단','불멸대']:tags;
}
const routeCounts={};
for(const city of Object.keys(cityNames)) for(const company of companySeeds.values()) {
  const route=quests.filter(q=>q.cities.includes(city)&&q.companies.includes(company));
  const ids=new Set(route.map(q=>q.id));
  const parents=new Set(route.flatMap(q=>q.previous.filter(id=>ids.has(id))));
  const leaves=route.filter(q=>!parents.has(q.id));
  assert.equal(leaves.length,1,`Unexpected unjoined branch: ${city}/${company}: ${leaves.map(q=>q.name)}`);
  assert.equal(leaves[0].group,groups.at(-1).id);
  routeCounts[`${city}/${company}`]=route.length;
}
const data={schemaVersion:1, fetchedAt:raw.fetchedAt, source:raw.source, sourceQuestCount:raw.quests.length, expansions, groups, quests};
const json=JSON.stringify(data,null,2);
// Prepare and validate completely before replacing the last working browser snapshot.
const target=new URL('data.js',root), temporary=new URL('.cache/data.js.tmp',root);
await writeFile(temporary, `/* Generated by scripts/build-data.mjs. Official public quest metadata only. */\nwindow.MSQ_DATA = ${json};\n`);
await rename(temporary,target);
console.log(`${quests.length} searchable quests (${raw.quests.length} source records). Route totals:`,routeCounts);
