const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),version='20260907-native2';
const routes={indigo:'근해 항로',ruby:'원양 항로',checklist:'물고기 도감'};
const copyright='<p>© SQUARE ENIX Published in Korea by Actoz Soft CO., LTD.</p><p>기재되어있는 회사 명 · 제품명 · 시스템 이름은 해당 소유자의 상표 또는 등록 상표입니다.</p>';
function header(page){return `<header class="journal-header"><a class="journal-brand" href="../indigo/"><img src="../img/journal-mark.svg" alt=""><span><strong>항해일지</strong><small>OCEAN FISHING JOURNAL</small></span></a><nav aria-label="낚시 메뉴">${Object.entries(routes).map(([id,title])=>`<a href="../${id}/" ${id===page?'aria-current="page"':''}>${title}</a>`).join('')}</nav>${page!=='sources'?'<div class="header-actions"><button id="openRecords" type="button">기록 관리</button><button class="text-button" type="button" data-lock-journal>잠그기</button></div>':''}</header>`;}
const footer=`<footer class="journal-footer"><div><span>항해일지 · 무료·비영리 팬 도구</span><a href="../sources/">출처 및 라이선스</a></div>${copyright}</footer>`;
const modal=`<dialog id="recordsDialog" aria-labelledby="recordsTitle"><header><div><h2 id="recordsTitle">내 낚시 기록</h2><p>근해·원양 기록을 함께 가져오고 백업해요.</p></div><button id="closeRecords" type="button">닫기</button></header><div class="dialog-content"><p id="backupStatus"></p><div class="button-row"><button id="importRecords" type="button">기록 가져오기</button><button id="exportRecords" type="button">JSON 내보내기</button><input id="importFile" type="file" accept=".json,application/json" hidden></div><p>기존 항해일지·원본 체크리스트·로컬 ZIP에서 내보낸 JSON을 읽을 수 있어요. 잡은 기록만 기존 수집 상태에 추가합니다.</p><form id="pasteImport"><label for="importText">복사한 기록 붙여넣기</label><textarea id="importText" rows="4" placeholder="Teamcraft 숫자 ID 배열 또는 체크리스트 JSON" required spellcheck="false"></textarea><button type="submit">붙여넣은 기록 가져오기</button></form><section class="teamcraft-transfer"><h3>Teamcraft로 보내기</h3><p>Teamcraft 낚시 수첩의 <strong>CarbunclePlushy에서 가져오기</strong>에 붙여넣으세요. 잡은 기록만 추가되며, 여기서 해제한 체크가 Teamcraft 기록을 삭제하지는 않아요.</p><button id="copyTeamcraft" type="button">Teamcraft용 기록 복사</button><div id="teamcraftFallback" hidden><label for="teamcraftOutput">복사할 내용</label><textarea id="teamcraftOutput" readonly rows="3"></textarea></div></section><p id="recordMessage" role="status" aria-live="polite"></p><p class="muted">기록은 이 브라우저에 저장됩니다. 브라우저를 바꾸거나 데이터를 지우기 전에 백업해 주세요.</p></div></dialog><aside id="notice" class="notice" hidden><span id="noticeText" role="status" aria-live="polite"></span><button id="undoCatch" type="button">실행 취소</button><button id="closeNotice" type="button">닫기</button></aside>`;
function planner(route){return `<section class="departure-board"><div class="section-heading"><h2><span class="number">01</span> 출항 시간표</h2><small>한국시간 (KST) · 매 홀수 시각부터 15분간 접수</small><button id="scheduleToggle" type="button" aria-expanded="false" aria-controls="scheduleRows">다음 시간 보기</button></div><div class="schedule-scroll"><table class="schedule-table"><thead><tr><th scope="col">접수 시작</th><th scope="col">남은 시간</th><th scope="col">목적지</th><th scope="col">미수집</th><th scope="col">전설어</th></tr></thead><tbody id="scheduleRows"></tbody></table></div><div class="schedule-actions"><label class="subtle-option"><input id="hideCompleted" type="checkbox"> 완료된 항로 숨기기</label><button id="moreVoyages" type="button" hidden>다음 24시간 더 보기</button></div><p class="muted small">업적작 가능은 세 구간에 공통 물고기군이 있다는 뜻이에요. *는 환해류가 필요한 구간을 포함하며, 날씨와 목표 마릿수 조건은 별도입니다.</p></section><div class="planner-layout"><aside class="planner-sidebar" aria-label="수집 현황과 낚시 목적"><section class="collection-summary"><span>나의 ${route==='indigo'?'근해':'원양'} 도감</span><div><strong id="collectionCount">0</strong><span>/ <span id="collectionTotal"></span></span></div><progress id="collectionProgress" max="1" value="0"></progress></section><section class="purpose-card"><fieldset class="purpose-picker"><legend>오늘의 낚시 목적</legend>${[['all','전체 보기','모든 물고기와 미끼'],['collection','도감 채우기','미수집과 조건 물고기'],['mission','선상과제/업적','필요한 물고기군 선택'],['score','고득점','모든 점수와 GP 추천']].map(([value,title,help])=>`<label><input type="radio" name="purpose" value="${value}" aria-label="${title}"><span><strong>${title}</strong><small>${help}</small></span></label>`).join('')}</fieldset><fieldset id="speciesOptions" hidden><legend>물고기군 · 여러 개 선택 가능</legend><div id="speciesChoices" class="species-choices"></div></fieldset><div id="scoreOptions" hidden><label for="scoreMode">사용할 기술</label><select id="scoreMode"><option value="TH">이중 + 삼중 낚아채기</option><option value="DH">이중 낚아채기만</option></select><label for="strategyGP">현재 GP</label><input id="strategyGP" type="number" min="0" max="9999" step="1" inputmode="numeric"><label for="strategyObjective">추천 기준</label><select id="strategyObjective"><option value="efficiency">GP당 추가 점수</option><option value="burst">한 번에 얻는 점수</option></select></div><p id="purposeHelp" class="muted small"></p><p id="collectionStatus" class="muted small" role="status"></p></section></aside><section class="fish-workspace"><header class="selected-route"><div><small>보고 있는 항로</small><h2 id="selectedTime"></h2><p id="selectedStops"></p></div><button id="returnFirst" type="button" hidden>첫 시간으로</button></header><div id="stopTabs" class="stop-tabs" role="tablist" aria-label="항로의 세 구간"></div><div id="fishPanels"></div></section></div>`;}
const checklist=`<section class="checklist-board"><div class="route-picker" aria-label="도감 항로"><button type="button" data-check-route="indigo" aria-pressed="true">근해</button><button type="button" data-check-route="ruby" aria-pressed="false">원양</button></div><div class="checklist-search"><label for="checklistSearch">물고기 검색</label><input id="checklistSearch" type="search" placeholder="이름 또는 초성으로 검색" autocomplete="off"><label class="subtle-option"><input id="checklistUncaught" type="checkbox"> 미획득만 보기</label><button id="clearSearch" type="button">검색 초기화</button></div><div class="checklist-status"><strong id="checklistCount"></strong><span id="checklistResults" role="status" aria-live="polite"></span></div><div id="checklistGroups"></div></section>`;
for(const [route,title] of Object.entries(routes)){
 const html=`<!doctype html><html lang="ko" data-entry-locked><head><meta charset="utf-8"><style>html[data-entry-locked] body>*:not(noscript){display:none!important}</style><script src="../scripts/entry.js?v=${version}"></script><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>항해일지 · ${title}</title><link rel="icon" href="../img/journal-mark.svg" type="image/svg+xml"><link rel="stylesheet" href="../css/app.css?v=${version}"><script defer src="../scripts/teamcraft-ids.js?v=${version}"></script><script defer src="../scripts/collection.js?v=${version}"></script><script defer src="../scripts/voyages.js?v=${version}"></script><script defer src="../scripts/app.js?v=${version}"></script></head><body data-page="${route}"><a class="skip-link" href="#mainContent">낚시 정보로 바로가기</a>${header(route)}<main id="mainContent"><section class="journal-hero"><div><p class="eyebrow">${route==='checklist'?'YOUR FISHING COLLECTION':route.toUpperCase()+' ROUTE / VOYAGE PLANNER'}</p><h1>${route==='checklist'?'한 마리씩, 채워가는 기록.':route==='indigo'?'오늘은, 근해로.':'오늘은, 원양으로.'}</h1><p>${route==='checklist'?'근해와 원양의 물고기를 모아 보고, 아직 만나지 못한 물고기를 찾아보세요.':'출항 시간을 고르고, 이번 항해에서 만날 물고기를 살펴보세요.'}</p></div><div class="voyage-stamp" aria-hidden="true"><small>OCEAN</small><strong>${route==='checklist'?'COLLECT':route.toUpperCase()}</strong><small>VOYAGE LOG</small></div></section><p id="loading" role="status">항해 자료를 불러오는 중이에요.</p><button id="retryLoad" type="button" hidden>다시 불러오기</button><div id="appContent" hidden>${route==='checklist'?checklist:planner(route)}</div></main>${footer}${modal}<noscript>항해일지를 사용하려면 JavaScript를 켜 주세요.</noscript></body></html>`;
 fs.writeFileSync(path.join(root,route,'index.html'),html+'\n');
}
// The entrance is our existing standalone page; update only its own asset paths.
const entryPath=path.join(root,'index.html');
let entry=fs.readFileSync(entryPath,'utf8').replace(/css\/(?:journal|app)\.css\?v=[^" ]+/g,'css/app.css?v='+version).replace(/scripts\/entry\.js\?v=[^" ]+/g,'scripts/entry.js?v='+version);
entry=entry.replace(/<footer class="entry-footer">[\s\S]*?<\/footer>/,`<footer class="entry-footer"><p>무료 · 비영리 팬 도구 · <a href="./sources/">출처 및 라이선스</a></p>${copyright}</footer>`);
fs.writeFileSync(entryPath,entry);
console.log('Built native planner and checklist pages.');
fs.mkdirSync(path.join(root,'sources'),{recursive:true});
fs.writeFileSync(path.join(root,'sources/index.html'),`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>항해일지 · 출처 및 라이선스</title><link rel="icon" href="../img/journal-mark.svg" type="image/svg+xml"><link rel="stylesheet" href="../css/app.css?v=${version}"></head><body>${header('sources')}<main class="sources-page"><p class="eyebrow">SOURCES &amp; CREDITS</p><h1>출처 및 라이선스</h1><article><p>항해일지는 무료·비영리로 제공하는 비공식 팬 도구입니다. SQUARE ENIX 및 액토즈소프트가 제작하거나 승인한 서비스가 아닙니다.</p><h2>프로그램</h2><p>화면, 시간표 계산, 검색, 필터, 수집 관리 및 GP 추천은 항해일지의 자체 구현입니다. OceanFishing.Boats의 실행 코드와 화면 라이브러리를 사용하지 않습니다.</p><h2>물고기 자료</h2><ul><li>낚시 수치·조건: <a href="https://oceanfishing.boats/about/">OceanFishing.Boats 데이터 제작진</a> · 데이터 수집 Tyo'to Tayuun, 한국어 자료 수리비용. <a href="https://github.com/netsua92/OceanFishing/tree/bbd67f90ed0285aa8e23d8f92f7f4d4c234441a2/fishdata">기준 데이터</a></li><li>원양 보완: <a href="https://docs.google.com/spreadsheets/d/1R0Nt8Ye7EAQtU8CXF1XRRj67iaFpUk1BXeDgt6abxsQ/edit">공개 측정표</a>와 Teamcraft 어종 목록 대조. <a href="../fishdata/ruby-verification.json">확인 내역</a></li><li>자료 기준일: 2026-09-07. 근해 140종·원양 119종. 자료가 없는 값은 미확인으로 표시하며 자동 갱신되지 않습니다.</li></ul><p>원본의 공개 데이터에 별도 재배포 라이선스는 확인되지 않았습니다. 이 사이트의 출처 표시와 자체 프로그램 구현은 해당 데이터에 새로운 이용 허락을 부여하지 않습니다.</p><h2>시간표 기준</h2><p>한국시간 매 홀수 시각의 접수와 항로·시간대 반복 규칙을 계산합니다. <a href="https://ffxiv.pf-n.co/ocean-fishing/about">공개된 반복 규칙 설명</a>과 <a href="https://ffxiv.consolegameswiki.com/wiki/Ocean_Fishing">항로 구성</a>을 참고하고 기존 공개 시간표와 대조했습니다. 게임 서버에 연결하거나 게임의 현재 날씨를 읽지는 않습니다.</p><h2>Teamcraft 자료</h2><p>아이템 ID와 어종 목록: <a href="https://github.com/ffxiv-teamcraft/ffxiv-teamcraft/tree/ceac70405b154d268bfc3bf6cda2776ac048a6d4/libs/data/src/lib/json">FFXIV Teamcraft 데이터</a>. Copyright (c) 2017 Flavien Normand. <a href="../licenses/Teamcraft-MIT.txt">MIT License 전문</a>을 함께 제공합니다.</p><h2>게임 이미지와 글꼴</h2><p>물고기 이미지는 FINAL FANTASY XIV 게임 자산입니다. 기존 사이트의 자체 제작 물고기군 도장 아이콘은 사용하지 않습니다.</p>${copyright}<p>글꼴: <a href="https://hangeul.naver.com/font/nanum">네이버 나눔스퀘어라운드</a> · <a href="../../fonts/nanum-square-round/OFL.txt">SIL Open Font License</a>.</p><h2>기록과 입장 화면</h2><p>낚시 기록은 브라우저에만 저장합니다. 기록 관리에서 백업·이전을 할 수 있어요. 비밀번호는 브라우저에서 작동하는 간단한 입장 장치이며, 공개된 파일을 보호하는 서버 인증이 아닙니다.</p></article></main>${footer}</body></html>\n`);
module.exports={header,footer,copyright,version};
