// Generated by scripts/update-data.mjs from the Korean official guide.
window.DUTY_DATA = {
  "schemaVersion": 1,
  "fetchedAt": "2026-09-06",
  "source": "https://guide.ff14.co.kr/lodestone/db/duty",
  "categories": [
    {
      "name": "던전",
      "count": 103
    },
    {
      "name": "길드 작전",
      "count": 14
    },
    {
      "name": "토벌전",
      "count": 104
    },
    {
      "name": "레이드",
      "count": 155
    },
    {
      "name": "PvP",
      "count": 16
    },
    {
      "name": "절 레이드",
      "count": 7
    },
    {
      "name": "멸 연합 레이드",
      "count": 1
    }
  ],
  "duties": [
    {
      "id": "dee4271da7e",
      "name": "사스타샤 침식 동굴",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 15,
      "itemLevel": null
    },
    {
      "id": "22c18cb4e68",
      "name": "탐타라 묘소",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 16,
      "itemLevel": null
    },
    {
      "id": "7c6972d1543",
      "name": "구리종 광산",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 17,
      "itemLevel": null
    },
    {
      "id": "510fa338ac2",
      "name": "할라탈리 수련장",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 20,
      "itemLevel": null
    },
    {
      "id": "3165d0d9203",
      "name": "토토라크 감옥",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 24,
      "itemLevel": null
    },
    {
      "id": "1dafce825e1",
      "name": "하우케타 별궁",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 28,
      "itemLevel": null
    },
    {
      "id": "859cc529697",
      "name": "브레이플록스의 야영지",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 32,
      "itemLevel": null
    },
    {
      "id": "2734d30a6f2",
      "name": "카른의 무너진 사원",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 35,
      "itemLevel": null
    },
    {
      "id": "ea16aa0f97d",
      "name": "나무꾼의 비명",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 38,
      "itemLevel": null
    },
    {
      "id": "53b6f68baad",
      "name": "돌방패 경계초소",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 41,
      "itemLevel": null
    },
    {
      "id": "91824420114",
      "name": "제멜 요새",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 44,
      "itemLevel": null
    },
    {
      "id": "b6915777cba",
      "name": "금빛 골짜기",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 47,
      "itemLevel": null
    },
    {
      "id": "3c97112d11b",
      "name": "방랑자의 궁전",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 45
    },
    {
      "id": "e94a2b5fea6",
      "name": "카스트룸 메리디아눔",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 42
    },
    {
      "id": "9937aa5a421",
      "name": "마도성 프라이토리움",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 42
    },
    {
      "id": "cca62880915",
      "name": "옛 암다포르 성",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 45
    },
    {
      "id": "1683ecdf6cc",
      "name": "시리우스 대등대",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 48
    },
    {
      "id": "9da5ad63ead",
      "name": "구리종 광산(어려움)",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 48
    },
    {
      "id": "87215a79974",
      "name": "하우케타 별궁(어려움)",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 48
    },
    {
      "id": "1f6c76dd406",
      "name": "옛 암다포르 시가지",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 55
    },
    {
      "id": "55980e7e3b5",
      "name": "할라탈리 수련장(어려움)",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 55
    },
    {
      "id": "8e90b0f03ae",
      "name": "브레이플록스의 야영지(어려움)",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 55
    },
    {
      "id": "e256e4547de",
      "name": "난파선의 섬",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 70
    },
    {
      "id": "d7b3725621c",
      "name": "탐타라 묘소(어려움)",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 70
    },
    {
      "id": "e0d811f0a6b",
      "name": "돌방패 경계초소(어려움)",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 70
    },
    {
      "id": "a89bb3fde6d",
      "name": "얼음외투 대빙벽",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 80
    },
    {
      "id": "c40d4ac8f8d",
      "name": "사스타샤 침식 동굴(어려움)",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 80
    },
    {
      "id": "71bd1da0cb4",
      "name": "카른의 무너진 사원(어려움)",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 80
    },
    {
      "id": "07b168db6f4",
      "name": "묵약의 탑",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 90
    },
    {
      "id": "94e69de74b8",
      "name": "방랑자의 궁전(어려움)",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 90
    },
    {
      "id": "c3bbfb061f2",
      "name": "옛 암다포르 성(어려움)",
      "category": "던전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 90
    },
    {
      "id": "d5736022993",
      "name": "어스름 요새",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 51,
      "itemLevel": 100
    },
    {
      "id": "5ea4ee6dacd",
      "name": "솜 알",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 53,
      "itemLevel": 105
    },
    {
      "id": "a4b4baddeaa",
      "name": "용의 둥지",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 55,
      "itemLevel": 110
    },
    {
      "id": "47abc7ba847",
      "name": "이슈가르드 교황청",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 57,
      "itemLevel": 115
    },
    {
      "id": "d3e0bd0074e",
      "name": "구브라 환상도서관",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 59,
      "itemLevel": 120
    },
    {
      "id": "26022fec090",
      "name": "마과학 연구소",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 142
    },
    {
      "id": "c09d7f0d58c",
      "name": "거두지 않는 섬",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 145
    },
    {
      "id": "b9cacb80f11",
      "name": "무한연속 박물함",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 145
    },
    {
      "id": "322c928d23a",
      "name": "성 모샨 식물원",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 170
    },
    {
      "id": "90433510008",
      "name": "시리우스 대등대(어려움)",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 170
    },
    {
      "id": "d9b8f3ac92f",
      "name": "거꾸로 선 탑",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 180
    },
    {
      "id": "55c679671bc",
      "name": "옛 암다포르 시가지(어려움)",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 180
    },
    {
      "id": "6b652893080",
      "name": "소르 카이",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 200
    },
    {
      "id": "c210394f48a",
      "name": "난파선의 섬(어려움)",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 200
    },
    {
      "id": "10b543ab57d",
      "name": "젤파톨",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 210
    },
    {
      "id": "18560552a6a",
      "name": "구브라 환상도서관(어려움)",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 210
    },
    {
      "id": "22d510d3637",
      "name": "바일사르 장성",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 230
    },
    {
      "id": "c1ea0f615b4",
      "name": "솜 알(어려움)",
      "category": "던전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 230
    },
    {
      "id": "e51c96fa74e",
      "name": "세이렌 해",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 61,
      "itemLevel": 240
    },
    {
      "id": "c5c6725d1b0",
      "name": "시스이 궁",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 63,
      "itemLevel": 245
    },
    {
      "id": "e79b3c57322",
      "name": "바르담 패도",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 65,
      "itemLevel": 250
    },
    {
      "id": "4e6ff665ed3",
      "name": "도마 성",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 67,
      "itemLevel": 255
    },
    {
      "id": "c12bd711ff3",
      "name": "카스트룸 아바니아",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 69,
      "itemLevel": 260
    },
    {
      "id": "5e1a7bf4569",
      "name": "알라미고",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 280
    },
    {
      "id": "b2cc27a0ed6",
      "name": "쿠가네 성",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 280
    },
    {
      "id": "d790ab2e84f",
      "name": "성도산 사원",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 280
    },
    {
      "id": "2a631760846",
      "name": "스칼라 유적",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 300
    },
    {
      "id": "bc73953dc39",
      "name": "지옥뚜껑",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 310
    },
    {
      "id": "10f56ad2032",
      "name": "무한연속 박물함(어려움)",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 310
    },
    {
      "id": "832472ee9d2",
      "name": "강엔 종묘",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 330
    },
    {
      "id": "56dcc8b6657",
      "name": "영구 초토지대",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 340
    },
    {
      "id": "d3302288da4",
      "name": "성 모샨 식물원(어려움)",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 340
    },
    {
      "id": "f75503e962e",
      "name": "김리트 황야",
      "category": "던전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 360
    },
    {
      "id": "e72435e2ebc",
      "name": "홀민스터",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 71,
      "itemLevel": 370
    },
    {
      "id": "9acd8b7a793",
      "name": "도느 메그",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 73,
      "itemLevel": 375
    },
    {
      "id": "9addfadf723",
      "name": "키타나 신굴",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 75,
      "itemLevel": 380
    },
    {
      "id": "06d18eda983",
      "name": "말리카 큰우물",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 77,
      "itemLevel": 385
    },
    {
      "id": "5ea9271171a",
      "name": "굴그 화산",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 79,
      "itemLevel": 390
    },
    {
      "id": "b06864ed0ca",
      "name": "아모로트",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 410
    },
    {
      "id": "b284e3ffd10",
      "name": "쌍둥이 시르쿠스",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 410
    },
    {
      "id": "64f917ff336",
      "name": "애나이더 아카데미아",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 410
    },
    {
      "id": "2714339e457",
      "name": "그랑 코스모스",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 430
    },
    {
      "id": "d656dfeebd0",
      "name": "애니드라스 아남네시스",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 440
    },
    {
      "id": "70164421abb",
      "name": "노르브란트",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 460
    },
    {
      "id": "75a6ed4a2f9",
      "name": "마토야의 공방",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 470
    },
    {
      "id": "30aa935e026",
      "name": "파글단",
      "category": "던전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 490
    },
    {
      "id": "ea013c32adf",
      "name": "조트 탑",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 81,
      "itemLevel": 500
    },
    {
      "id": "915693d5dc6",
      "name": "바브일 탑",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 83,
      "itemLevel": 505
    },
    {
      "id": "c34a6540f19",
      "name": "바나스파티",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 85,
      "itemLevel": 510
    },
    {
      "id": "59bc9590194",
      "name": "휘페르보레아 조물원",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 87,
      "itemLevel": 515
    },
    {
      "id": "9bf8cfa2bf3",
      "name": "아이티온 별현미경",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 89,
      "itemLevel": 520
    },
    {
      "id": "36d46103b78",
      "name": "잔해별",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 540
    },
    {
      "id": "967e67a696b",
      "name": "스마일턴",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 540
    },
    {
      "id": "81373618921",
      "name": "스티그마-4",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 540
    },
    {
      "id": "aa54f7c0f95",
      "name": "알자달 해저 유적",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 560
    },
    {
      "id": "6135f1eb300",
      "name": "트로이아 궁정",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 575
    },
    {
      "id": "792e67706b4",
      "name": "라피스 마날리스",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 590
    },
    {
      "id": "0dff0394534",
      "name": "함 섬",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 605
    },
    {
      "id": "49a97bd9e40",
      "name": "달의 지하계곡",
      "category": "던전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 620
    },
    {
      "id": "a23267fb7f1",
      "name": "이후이카 투무",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 91,
      "itemLevel": 630
    },
    {
      "id": "d2b1e0330eb",
      "name": "워코 조모",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 93,
      "itemLevel": 635
    },
    {
      "id": "5c5eb2cb875",
      "name": "하늘심연 세노테",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 95,
      "itemLevel": 640
    },
    {
      "id": "b3061a7b901",
      "name": "뱅가드",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 97,
      "itemLevel": 645
    },
    {
      "id": "c3e5463873d",
      "name": "오리제닉스",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 99,
      "itemLevel": 650
    },
    {
      "id": "1f3c36f74df",
      "name": "알렉산드리아",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 670
    },
    {
      "id": "f3b9a1b9155",
      "name": "사보텐더 계곡",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 670
    },
    {
      "id": "126c88aeb45",
      "name": "헤매는 성",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 670
    },
    {
      "id": "0de18774e83",
      "name": "유웨야와타",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 690
    },
    {
      "id": "af3eb37f191",
      "name": "언더킵",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 705
    },
    {
      "id": "97c1c8e073e",
      "name": "메인 터미널",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 720
    },
    {
      "id": "e60e156423a",
      "name": "안개여로",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 735
    },
    {
      "id": "941e2187bf5",
      "name": "클리테우스 마도 공장",
      "category": "던전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 750
    },
    {
      "id": "ad5d654254a",
      "name": "집단전 훈련을 완수하라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 10,
      "itemLevel": null
    },
    {
      "id": "6298ecf0173",
      "name": "방황하는 사령을 쓰러뜨려라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 10,
      "itemLevel": null
    },
    {
      "id": "d88ac9de314",
      "name": "관문을 돌파하고 최심부의 적을 쓰러뜨려라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 15,
      "itemLevel": null
    },
    {
      "id": "27cbe8471d8",
      "name": "길거북을 사로잡아라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 15,
      "itemLevel": null
    },
    {
      "id": "5afc32f405e",
      "name": "독성 요괴꽃을 제거하라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 20,
      "itemLevel": null
    },
    {
      "id": "7907cc624e5",
      "name": "무법자 집단 '나나니단'을 섬멸하라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 20,
      "itemLevel": null
    },
    {
      "id": "3fdfd0e0418",
      "name": "몽환의 브라크시오를 쓰러뜨려라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 25,
      "itemLevel": null
    },
    {
      "id": "034e27ce6ae",
      "name": "폭탄광 고블린 군단을 섬멸하라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 25,
      "itemLevel": null
    },
    {
      "id": "8d20ead4920",
      "name": "오염원 몰볼을 쓰러뜨려라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "e21cfcfa806",
      "name": "갱도에 나타난 요마 부소를 쓰러뜨려라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "c5a89bc115b",
      "name": "무적의 부하를 조종하는 요마를 쓰러뜨려라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 35,
      "itemLevel": null
    },
    {
      "id": "2eded8fd433",
      "name": "봄을 거느린 '봄 여왕'을 쓰러뜨려라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 35,
      "itemLevel": null
    },
    {
      "id": "8984c14e734",
      "name": "불길한 진형을 짜는 요마를 섬멸하라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 40,
      "itemLevel": null
    },
    {
      "id": "b436abc3c41",
      "name": "세 거인족을 제압하여 유물을 지켜내라!",
      "category": "길드 작전",
      "expansion": "신생 에오르제아",
      "level": 40,
      "itemLevel": null
    },
    {
      "id": "d318e4e7e5a",
      "name": "이프리트 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 20,
      "itemLevel": null
    },
    {
      "id": "c1bb66d8c0d",
      "name": "타이탄 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 34,
      "itemLevel": null
    },
    {
      "id": "aaee2a5d194",
      "name": "가루다 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 44,
      "itemLevel": null
    },
    {
      "id": "239fbe1e8de",
      "name": "알테마 웨폰 파괴작전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 42
    },
    {
      "id": "c31514e5f5e",
      "name": "아씨엔 나브리알레스 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 90
    },
    {
      "id": "3e9ad082980",
      "name": "도름 키마이라 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 52
    },
    {
      "id": "c7d6b70be82",
      "name": "하이드라 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 52
    },
    {
      "id": "25b2ff0126c",
      "name": "길가메시 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 50
    },
    {
      "id": "467a02c57b3",
      "name": "아마지나배 투기대회 결승전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 80
    },
    {
      "id": "ff94bc7e233",
      "name": "진 길가메시 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 90
    },
    {
      "id": "9d9542db9db",
      "name": "진 이프리트 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 49
    },
    {
      "id": "eec2b4e2fbc",
      "name": "진 가루다 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 52
    },
    {
      "id": "bc3791a1dfd",
      "name": "진 타이탄 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 57
    },
    {
      "id": "43a5a9402fb",
      "name": "선왕 모그루 모그 XII세 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 54
    },
    {
      "id": "7cf438b6efe",
      "name": "진 리바이어선 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 60
    },
    {
      "id": "ed444c7acd3",
      "name": "진 라무 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 65
    },
    {
      "id": "e144969a90a",
      "name": "진 시바 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 80
    },
    {
      "id": "5f3f910214e",
      "name": "투신 오딘 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 95
    },
    {
      "id": "66ae49e0046",
      "name": "궁극의 환상 알테마 웨폰 파괴작전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 61
    },
    {
      "id": "9842c2bdc58",
      "name": "극 가루다 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 65
    },
    {
      "id": "4e50507ad4c",
      "name": "극 타이탄 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 67
    },
    {
      "id": "6978819142c",
      "name": "극 이프리트 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 70
    },
    {
      "id": "8906bc1280a",
      "name": "극왕 모그루 모그 XII세 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 80
    },
    {
      "id": "e804f3b8b97",
      "name": "극 리바이어선 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 80
    },
    {
      "id": "cefca6483e5",
      "name": "극 라무 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 85
    },
    {
      "id": "4bf35b95f14",
      "name": "극 시바 토벌전",
      "category": "토벌전",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 95
    },
    {
      "id": "37b1cff3e79",
      "name": "진 라바나 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 53,
      "itemLevel": null
    },
    {
      "id": "5f1b4362363",
      "name": "진 비스마르크 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 57,
      "itemLevel": null
    },
    {
      "id": "ff779c66560",
      "name": "나이츠 오브 라운드 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 142
    },
    {
      "id": "86cfd7a94a8",
      "name": "니드호그 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 205
    },
    {
      "id": "914e46eb26f",
      "name": "마신 세피로트 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 190
    },
    {
      "id": "206a8369051",
      "name": "여신 소피아 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 220
    },
    {
      "id": "4e265a3eced",
      "name": "귀신 주르반 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 235
    },
    {
      "id": "326a8edafad",
      "name": "극 비스마르크 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 165
    },
    {
      "id": "f9413653e56",
      "name": "극 라바나 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 175
    },
    {
      "id": "e3aeb0747be",
      "name": "극 나이츠 오브 라운드 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 190
    },
    {
      "id": "5a3c9c4fa40",
      "name": "극 니드호그 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 220
    },
    {
      "id": "412aec8660e",
      "name": "극 마신 세피로트 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 205
    },
    {
      "id": "1820d2beabc",
      "name": "극 여신 소피아 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 235
    },
    {
      "id": "84ced1731eb",
      "name": "극 귀신 주르반 토벌전",
      "category": "토벌전",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 250
    },
    {
      "id": "37f52ddb19b",
      "name": "스사노오 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 63,
      "itemLevel": null
    },
    {
      "id": "0b5cd739ef5",
      "name": "락슈미 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 67,
      "itemLevel": null
    },
    {
      "id": "e7f2a59aaf1",
      "name": "신룡 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 280
    },
    {
      "id": "0456095b013",
      "name": "츠쿠요미 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 335
    },
    {
      "id": "575a8f6a948",
      "name": "진 요우진보 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 365
    },
    {
      "id": "5e896195f40",
      "name": "리오레우스 수렵전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 320
    },
    {
      "id": "3e8ee9f8e98",
      "name": "백호 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 325
    },
    {
      "id": "0bb7a09e177",
      "name": "주작 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 355
    },
    {
      "id": "3872aa603e0",
      "name": "청룡 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 365
    },
    {
      "id": "d5b152fa4b4",
      "name": "극 스사노오 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 300
    },
    {
      "id": "f33ee9ce371",
      "name": "극 락슈미 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 300
    },
    {
      "id": "76d334b99e2",
      "name": "극 신룡 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 320
    },
    {
      "id": "246b2ff14bf",
      "name": "극 츠쿠요미 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 350
    },
    {
      "id": "0ad0c0dbcd3",
      "name": "극 리오레우스 수렵전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 350
    },
    {
      "id": "caaf9cad5e0",
      "name": "극 백호 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 340
    },
    {
      "id": "10e75d5ce80",
      "name": "극 주작 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 370
    },
    {
      "id": "61eae94c75a",
      "name": "극 청룡 토벌전",
      "category": "토벌전",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 380
    },
    {
      "id": "f7a52f14e83",
      "name": "티타니아 토벌전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 73,
      "itemLevel": null
    },
    {
      "id": "6858b374c73",
      "name": "이노센스 토벌전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 79,
      "itemLevel": null
    },
    {
      "id": "321fd159682",
      "name": "하데스 토벌전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 410
    },
    {
      "id": "d58875864be",
      "name": "루비 웨폰 파괴작전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 455
    },
    {
      "id": "e62003f42c2",
      "name": "빛의 전사 토벌전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 465
    },
    {
      "id": "4c3975dacb6",
      "name": "에메랄드 웨폰 파괴작전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 485
    },
    {
      "id": "aa56c6c81f2",
      "name": "다이아몬드 웨폰 포획작전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 495
    },
    {
      "id": "a0b3834c5d9",
      "name": "극 티타니아 토벌전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 430
    },
    {
      "id": "9f55d76c659",
      "name": "극 이노센스 토벌전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 430
    },
    {
      "id": "ad5521cac0d",
      "name": "극 하데스 토벌전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 450
    },
    {
      "id": "8a3e1760919",
      "name": "극 루비 웨폰 파괴작전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 470
    },
    {
      "id": "fba9d509110",
      "name": "극 보즈야 추억전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 470
    },
    {
      "id": "d93b9ae2a34",
      "name": "극 빛의 전사 토벌전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 480
    },
    {
      "id": "950545da440",
      "name": "극 에메랄드 웨폰 파괴작전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 500
    },
    {
      "id": "19d0fd71f66",
      "name": "극 다이아몬드 웨폰 포획작전",
      "category": "토벌전",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 510
    },
    {
      "id": "0ec40757254",
      "name": "조디아크 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 83,
      "itemLevel": null
    },
    {
      "id": "dc51d7c2abd",
      "name": "하이델린 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 89,
      "itemLevel": null
    },
    {
      "id": "f74becf42ce",
      "name": "종언의 결전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 540
    },
    {
      "id": "4c8d2ff8db1",
      "name": "바르바리차 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 585
    },
    {
      "id": "d507cfbc2ee",
      "name": "루비칸테 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 595
    },
    {
      "id": "455ef52165f",
      "name": "골베자 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 615
    },
    {
      "id": "3aae319c9b2",
      "name": "제로무스 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 625
    },
    {
      "id": "b0c2b5efa48",
      "name": "아수라 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 625
    },
    {
      "id": "435cbb84c32",
      "name": "극 조디아크 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 560
    },
    {
      "id": "328162d734a",
      "name": "극 하이델린 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 560
    },
    {
      "id": "260caa43959",
      "name": "종극의 결전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 580
    },
    {
      "id": "72c1cef271a",
      "name": "극 바르바리차 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 600
    },
    {
      "id": "dddb0b153e4",
      "name": "극 루비칸테 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 610
    },
    {
      "id": "8eb0a1aa316",
      "name": "극 골베자 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 630
    },
    {
      "id": "eec4c21096e",
      "name": "극 제로무스 토벌전",
      "category": "토벌전",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 640
    },
    {
      "id": "5de535790ce",
      "name": "발리가르만다 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 93,
      "itemLevel": null
    },
    {
      "id": "99d1fd992bb",
      "name": "조라쟈 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 99,
      "itemLevel": null
    },
    {
      "id": "9d3819988bc",
      "name": "이터널 퀸 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 670
    },
    {
      "id": "b80ea021025",
      "name": "젤레니아 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 715
    },
    {
      "id": "975d83e5b41",
      "name": "영원한 어둠 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 725
    },
    {
      "id": "b0796e7c856",
      "name": "수호룡 알슈베르도 수렵전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 725
    },
    {
      "id": "c352dd60d71",
      "name": "글라시아 라볼라스 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 745
    },
    {
      "id": "2c82e3130e1",
      "name": "에누오 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 755
    },
    {
      "id": "71c8e2c4ab4",
      "name": "극 발리가르만다 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 690
    },
    {
      "id": "b7e0a867f42",
      "name": "극 조라쟈 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 690
    },
    {
      "id": "80c0e53db64",
      "name": "극 이터널 퀸 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 710
    },
    {
      "id": "afecec9fa18",
      "name": "극 젤레니아 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 730
    },
    {
      "id": "ec052ed4f4f",
      "name": "극 영원한 어둠 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 740
    },
    {
      "id": "8b5a4a07569",
      "name": "극 수호룡 알슈베르도 수렵전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 740
    },
    {
      "id": "2e80f652c99",
      "name": "극 글라시아 라볼라스 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 760
    },
    {
      "id": "b6c80b13c51",
      "name": "극 에누오 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 770
    },
    {
      "id": "11d34d29f06",
      "name": "환 신룡 토벌전",
      "category": "토벌전",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 690
    },
    {
      "id": "fc38048f4fc",
      "name": "크리스탈 타워: 고대인의 미궁",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 50
    },
    {
      "id": "9cf6ef52d99",
      "name": "크리스탈 타워: 시르쿠스 탑",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 70
    },
    {
      "id": "a70105d73ff",
      "name": "크리스탈 타워: 어둠의 세계",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 90
    },
    {
      "id": "4780faab7a0",
      "name": "대미궁 바하무트: 해후편 1",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 70
    },
    {
      "id": "3ed3f771347",
      "name": "대미궁 바하무트: 해후편 2",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 73
    },
    {
      "id": "9c3f7a5e183",
      "name": "대미궁 바하무트: 해후편 3",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 70
    },
    {
      "id": "4e2aa78e7d6",
      "name": "대미궁 바하무트: 해후편 4",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 77
    },
    {
      "id": "21448253e26",
      "name": "대미궁 바하무트: 해후편 5",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 82
    },
    {
      "id": "4125cd2c95a",
      "name": "대미궁 바하무트: 침공편 1",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 90
    },
    {
      "id": "7646c8251a8",
      "name": "대미궁 바하무트: 침공편 2",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 95
    },
    {
      "id": "6d621395a14",
      "name": "대미궁 바하무트: 침공편 3",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 100
    },
    {
      "id": "f22083ab587",
      "name": "대미궁 바하무트: 침공편 4",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 105
    },
    {
      "id": "57a3d7a6f70",
      "name": "대미궁 바하무트: 진성편 1",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 110
    },
    {
      "id": "2cd8a5ec564",
      "name": "대미궁 바하무트: 진성편 2",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 115
    },
    {
      "id": "cf4cf3f03a6",
      "name": "대미궁 바하무트: 진성편 3",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 120
    },
    {
      "id": "c1d3ec5662f",
      "name": "대미궁 바하무트: 진성편 4",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 123
    },
    {
      "id": "b237a2b06be",
      "name": "대미궁 바하무트: 침공편(영웅) 1",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 105
    },
    {
      "id": "98f84b5941e",
      "name": "대미궁 바하무트: 침공편(영웅) 2",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 105
    },
    {
      "id": "90ae33b54be",
      "name": "대미궁 바하무트: 침공편(영웅) 3",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 105
    },
    {
      "id": "7f95681c3ed",
      "name": "대미궁 바하무트: 침공편(영웅) 4",
      "category": "레이드",
      "expansion": "신생 에오르제아",
      "level": 50,
      "itemLevel": 105
    },
    {
      "id": "02f46089740",
      "name": "보이드의 방주",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 175
    },
    {
      "id": "60cf92904b2",
      "name": "금기도시 마하",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 205
    },
    {
      "id": "4ded102beb0",
      "name": "둔 스카",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 235
    },
    {
      "id": "b4738e0b13a",
      "name": "기공성 알렉산더: 기동편 1",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 170
    },
    {
      "id": "5ff4f886ed4",
      "name": "기공성 알렉산더: 기동편 2",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 170
    },
    {
      "id": "54d17a5c3fc",
      "name": "기공성 알렉산더: 기동편 3",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 170
    },
    {
      "id": "5a64f37bdda",
      "name": "기공성 알렉산더: 기동편 4",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 170
    },
    {
      "id": "86c6ab9df5c",
      "name": "기공성 알렉산더: 율동편 1",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 200
    },
    {
      "id": "894b2a599f1",
      "name": "기공성 알렉산더: 율동편 2",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 200
    },
    {
      "id": "2bb14d91fa2",
      "name": "기공성 알렉산더: 율동편 3",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 200
    },
    {
      "id": "fdedddb6a38",
      "name": "기공성 알렉산더: 율동편 4",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 200
    },
    {
      "id": "da8bcee06f4",
      "name": "기공성 알렉산더: 천동편 1",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 230
    },
    {
      "id": "803567b07f6",
      "name": "기공성 알렉산더: 천동편 2",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 230
    },
    {
      "id": "6f88fbc2d0a",
      "name": "기공성 알렉산더: 천동편 3",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 230
    },
    {
      "id": "c676012a31a",
      "name": "기공성 알렉산더: 천동편 4",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 230
    },
    {
      "id": "6ad25e207dd",
      "name": "기공성 알렉산더: 기동편(영웅) 1",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 190
    },
    {
      "id": "82360afdceb",
      "name": "기공성 알렉산더: 기동편(영웅) 2",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 195
    },
    {
      "id": "9afe358c025",
      "name": "기공성 알렉산더: 기동편(영웅) 3",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 200
    },
    {
      "id": "d5066d66ca9",
      "name": "기공성 알렉산더: 기동편(영웅) 4",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 205
    },
    {
      "id": "6cf723f62e2",
      "name": "기공성 알렉산더: 율동편(영웅) 1",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 215
    },
    {
      "id": "6688bb88120",
      "name": "기공성 알렉산더: 율동편(영웅) 2",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 220
    },
    {
      "id": "c2b98749368",
      "name": "기공성 알렉산더: 율동편(영웅) 3",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 225
    },
    {
      "id": "36031fb4c13",
      "name": "기공성 알렉산더: 율동편(영웅) 4",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 225
    },
    {
      "id": "365979bcdb5",
      "name": "기공성 알렉산더: 천동편(영웅) 1",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 245
    },
    {
      "id": "c9ce9321388",
      "name": "기공성 알렉산더: 천동편(영웅) 2",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 250
    },
    {
      "id": "0caebff3fb9",
      "name": "기공성 알렉산더: 천동편(영웅) 3",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 255
    },
    {
      "id": "c2d46c8b466",
      "name": "기공성 알렉산더: 천동편(영웅) 4",
      "category": "레이드",
      "expansion": "창천의 이슈가르드",
      "level": 60,
      "itemLevel": 255
    },
    {
      "id": "f5c80e86c10",
      "name": "왕도 라바나스터",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 305
    },
    {
      "id": "57d953f74ba",
      "name": "대등대 리도르아나",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 335
    },
    {
      "id": "bf7b76fa52a",
      "name": "오본느 수도원",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 365
    },
    {
      "id": "68141758555",
      "name": "차원의 틈 오메가: 델타편 1",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 295
    },
    {
      "id": "efe7030e570",
      "name": "차원의 틈 오메가: 델타편 2",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 295
    },
    {
      "id": "84a3a5d1310",
      "name": "차원의 틈 오메가: 델타편 3",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 295
    },
    {
      "id": "e5c6bf428c6",
      "name": "차원의 틈 오메가: 델타편 4",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 295
    },
    {
      "id": "5e32ae03d6b",
      "name": "차원의 틈 오메가: 시그마편 1",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 325
    },
    {
      "id": "2c4d73d43d3",
      "name": "차원의 틈 오메가: 시그마편 2",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 325
    },
    {
      "id": "e223216d566",
      "name": "차원의 틈 오메가: 시그마편 3",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 325
    },
    {
      "id": "ba6980504fe",
      "name": "차원의 틈 오메가: 시그마편 4",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 325
    },
    {
      "id": "5a0a06b5e50",
      "name": "차원의 틈 오메가: 알파편 1",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 355
    },
    {
      "id": "6ead9fead2a",
      "name": "차원의 틈 오메가: 알파편 2",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 355
    },
    {
      "id": "11156c24a1b",
      "name": "차원의 틈 오메가: 알파편 3",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 355
    },
    {
      "id": "e3478e88f21",
      "name": "차원의 틈 오메가: 알파편 4",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 355
    },
    {
      "id": "a9d22a61ece",
      "name": "차원의 틈 오메가: 델타편(영웅) 1",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 310
    },
    {
      "id": "1d5c9c31254",
      "name": "차원의 틈 오메가: 델타편(영웅) 2",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 315
    },
    {
      "id": "e2e348befa3",
      "name": "차원의 틈 오메가: 델타편(영웅) 3",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 320
    },
    {
      "id": "edf2f55a2ec",
      "name": "차원의 틈 오메가: 델타편(영웅) 4",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 320
    },
    {
      "id": "42cd8cb927c",
      "name": "차원의 틈 오메가: 시그마편(영웅) 1",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 340
    },
    {
      "id": "6b4a773fd82",
      "name": "차원의 틈 오메가: 시그마편(영웅) 2",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 345
    },
    {
      "id": "eff08ea2371",
      "name": "차원의 틈 오메가: 시그마편(영웅) 3",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 350
    },
    {
      "id": "5a3cf5bf7fb",
      "name": "차원의 틈 오메가: 시그마편(영웅) 4",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 350
    },
    {
      "id": "1d2ffe94998",
      "name": "차원의 틈 오메가: 알파편(영웅) 1",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 370
    },
    {
      "id": "031a8a25baf",
      "name": "차원의 틈 오메가: 알파편(영웅) 2",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 375
    },
    {
      "id": "14d65e0f20b",
      "name": "차원의 틈 오메가: 알파편(영웅) 3",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 380
    },
    {
      "id": "0c0630eddf9",
      "name": "차원의 틈 오메가: 알파편(영웅) 4",
      "category": "레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": 380
    },
    {
      "id": "9145014afa2",
      "name": "복제된 공장 폐허",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 435
    },
    {
      "id": "e4fa57a2f0d",
      "name": "인형들의 군사 기지",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 465
    },
    {
      "id": "60e868561a1",
      "name": "희망의 포대: '탑'",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 495
    },
    {
      "id": "ab59c445acf",
      "name": "희망의 낙원 에덴: 각성편 1",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 425
    },
    {
      "id": "7a8ea76e725",
      "name": "희망의 낙원 에덴: 각성편 2",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 425
    },
    {
      "id": "25892e43595",
      "name": "희망의 낙원 에덴: 각성편 3",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 425
    },
    {
      "id": "34e2e83d3de",
      "name": "희망의 낙원 에덴: 각성편 4",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 425
    },
    {
      "id": "93452bd3d92",
      "name": "희망의 낙원 에덴: 공명편 1",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 455
    },
    {
      "id": "08e64cf80e1",
      "name": "희망의 낙원 에덴: 공명편 2",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 455
    },
    {
      "id": "84b28194899",
      "name": "희망의 낙원 에덴: 공명편 3",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 455
    },
    {
      "id": "45ebc1c1fb6",
      "name": "희망의 낙원 에덴: 공명편 4",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 455
    },
    {
      "id": "97999dde34d",
      "name": "희망의 낙원 에덴: 재생편 1",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 485
    },
    {
      "id": "19de069d2d5",
      "name": "희망의 낙원 에덴: 재생편 2",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 485
    },
    {
      "id": "b5b7ab2405c",
      "name": "희망의 낙원 에덴: 재생편 3",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 485
    },
    {
      "id": "0a5f0cdd470",
      "name": "희망의 낙원 에덴: 재생편 4",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 485
    },
    {
      "id": "cce150e321f",
      "name": "희망의 낙원 에덴: 각성편(영웅) 1",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 440
    },
    {
      "id": "0818b98ece8",
      "name": "희망의 낙원 에덴: 각성편(영웅) 2",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 445
    },
    {
      "id": "5ba087dc61a",
      "name": "희망의 낙원 에덴: 각성편(영웅) 3",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 450
    },
    {
      "id": "20e63736c81",
      "name": "희망의 낙원 에덴: 각성편(영웅) 4",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 450
    },
    {
      "id": "66d0ee81883",
      "name": "희망의 낙원 에덴: 공명편(영웅) 1",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 470
    },
    {
      "id": "bba455d7591",
      "name": "희망의 낙원 에덴: 공명편(영웅) 2",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 475
    },
    {
      "id": "66adb2d964e",
      "name": "희망의 낙원 에덴: 공명편(영웅) 3",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 480
    },
    {
      "id": "10e138e220c",
      "name": "희망의 낙원 에덴: 공명편(영웅) 4",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 480
    },
    {
      "id": "ff5fee34d12",
      "name": "희망의 낙원 에덴: 재생편(영웅) 1",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 500
    },
    {
      "id": "64c8f090dc3",
      "name": "희망의 낙원 에덴: 재생편(영웅) 2",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 505
    },
    {
      "id": "6afc9bc9aee",
      "name": "희망의 낙원 에덴: 재생편(영웅) 3",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 510
    },
    {
      "id": "b49091cec54",
      "name": "희망의 낙원 에덴: 재생편(영웅) 4",
      "category": "레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": 510
    },
    {
      "id": "5b2bd74bd65",
      "name": "찬란한 신역 아글라이아",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 565
    },
    {
      "id": "6a4c4fd6d54",
      "name": "환희의 신역 에우프로시네",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 595
    },
    {
      "id": "6f78305dcab",
      "name": "번영의 신역 탈레이아",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 625
    },
    {
      "id": "42cb1dee850",
      "name": "마의 전당 판데모니움: 변옥편 1",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 565
    },
    {
      "id": "5e879e7e6b5",
      "name": "마의 전당 판데모니움: 변옥편 2",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 565
    },
    {
      "id": "dee344d6aa0",
      "name": "마의 전당 판데모니움: 변옥편 3",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 565
    },
    {
      "id": "999a70cd4c6",
      "name": "마의 전당 판데모니움: 변옥편 4",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 565
    },
    {
      "id": "60022c94e99",
      "name": "마의 전당 판데모니움: 변옥편(영웅) 1",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 570
    },
    {
      "id": "a373bf4ef95",
      "name": "마의 전당 판데모니움: 변옥편(영웅) 2",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 575
    },
    {
      "id": "a187188be0f",
      "name": "마의 전당 판데모니움: 변옥편(영웅) 3",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 580
    },
    {
      "id": "463f6d71980",
      "name": "마의 전당 판데모니움: 변옥편(영웅) 4",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 580
    },
    {
      "id": "f81434724b5",
      "name": "마의 전당 판데모니움: 연옥편 1",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 585
    },
    {
      "id": "cbc74d066d0",
      "name": "마의 전당 판데모니움: 연옥편 2",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 585
    },
    {
      "id": "bb9bac94e22",
      "name": "마의 전당 판데모니움: 연옥편 3",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 585
    },
    {
      "id": "350d3f10d44",
      "name": "마의 전당 판데모니움: 연옥편 4",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 585
    },
    {
      "id": "8f91d8c5311",
      "name": "마의 전당 판데모니움: 연옥편(영웅) 1",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 600
    },
    {
      "id": "41ed84b692f",
      "name": "마의 전당 판데모니움: 연옥편(영웅) 2",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 605
    },
    {
      "id": "9e76ad80961",
      "name": "마의 전당 판데모니움: 연옥편(영웅) 3",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 610
    },
    {
      "id": "d6de8662221",
      "name": "마의 전당 판데모니움: 연옥편(영웅) 4",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 610
    },
    {
      "id": "f44da74edc1",
      "name": "마의 전당 판데모니움: 천옥편 1",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 615
    },
    {
      "id": "e79338db390",
      "name": "마의 전당 판데모니움: 천옥편 2",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 615
    },
    {
      "id": "933dcb865d2",
      "name": "마의 전당 판데모니움: 천옥편 3",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 615
    },
    {
      "id": "ccde89dc68b",
      "name": "마의 전당 판데모니움: 천옥편 4",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 615
    },
    {
      "id": "aec801f5696",
      "name": "마의 전당 판데모니움: 천옥편(영웅) 1",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 630
    },
    {
      "id": "825da19a6fc",
      "name": "마의 전당 판데모니움: 천옥편(영웅) 2",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 635
    },
    {
      "id": "9adb1e731ae",
      "name": "마의 전당 판데모니움: 천옥편(영웅) 3",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 640
    },
    {
      "id": "b8a237d0914",
      "name": "마의 전당 판데모니움: 천옥편(영웅) 4",
      "category": "레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": 640
    },
    {
      "id": "d966ab55a02",
      "name": "쥬노: 첫 번째 반향세계",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 695
    },
    {
      "id": "a8dda42d624",
      "name": "산도리아: 두 번째 반향세계",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 725
    },
    {
      "id": "82362c7fc16",
      "name": "윈더스: 세 번째 반향세계",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 755
    },
    {
      "id": "b9830c3e072",
      "name": "아르카디아 선수권: 라이트헤비급 1",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 685
    },
    {
      "id": "0ec6615acb3",
      "name": "아르카디아 선수권: 라이트헤비급 2",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 685
    },
    {
      "id": "488453fce11",
      "name": "아르카디아 선수권: 라이트헤비급 3",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 685
    },
    {
      "id": "0fc137681c6",
      "name": "아르카디아 선수권: 라이트헤비급 4",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 685
    },
    {
      "id": "12d5cc71b6a",
      "name": "아르카디아 선수권: 라이트헤비급(영웅) 1",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 700
    },
    {
      "id": "c65a0c49a19",
      "name": "아르카디아 선수권: 라이트헤비급(영웅) 2",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 705
    },
    {
      "id": "a7cc6c1f864",
      "name": "아르카디아 선수권: 라이트헤비급(영웅) 3",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 710
    },
    {
      "id": "a279030d4fa",
      "name": "아르카디아 선수권: 라이트헤비급(영웅) 4",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 710
    },
    {
      "id": "2b22709353d",
      "name": "아르카디아 선수권: 크루저급 1",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 715
    },
    {
      "id": "d549881c396",
      "name": "아르카디아 선수권: 크루저급 2",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 715
    },
    {
      "id": "fa6ab778a9f",
      "name": "아르카디아 선수권: 크루저급 3",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 715
    },
    {
      "id": "0a2b646f87c",
      "name": "아르카디아 선수권: 크루저급 4",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 715
    },
    {
      "id": "72d22ea1b59",
      "name": "아르카디아 선수권: 크루저급(영웅) 1",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 730
    },
    {
      "id": "54b69396885",
      "name": "아르카디아 선수권: 크루저급(영웅) 2",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 735
    },
    {
      "id": "2ce061baeb1",
      "name": "아르카디아 선수권: 크루저급(영웅) 3",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 740
    },
    {
      "id": "778f1525435",
      "name": "아르카디아 선수권: 크루저급(영웅) 4",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 740
    },
    {
      "id": "9045e0d22f1",
      "name": "아르카디아 선수권: 헤비급 1",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 745
    },
    {
      "id": "a61577e01bb",
      "name": "아르카디아 선수권: 헤비급 2",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 745
    },
    {
      "id": "69f27339675",
      "name": "아르카디아 선수권: 헤비급 3",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 745
    },
    {
      "id": "c9c0643eb85",
      "name": "아르카디아 선수권: 헤비급 4",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 745
    },
    {
      "id": "c417846e130",
      "name": "아르카디아 선수권: 헤비급(영웅) 1",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 760
    },
    {
      "id": "bbe4952d364",
      "name": "아르카디아 선수권: 헤비급(영웅) 2",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 765
    },
    {
      "id": "fd1c9134d13",
      "name": "아르카디아 선수권: 헤비급(영웅) 3",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 770
    },
    {
      "id": "548016adc67",
      "name": "아르카디아 선수권: 헤비급(영웅) 4",
      "category": "레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 770
    },
    {
      "id": "2dcf7f22cdf",
      "name": "팔라이스트라",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "8fd8923657e",
      "name": "팔라이스트라",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "d8ed28fad46",
      "name": "크리스탈라인 컨플릭트(팔라이스트라: 친선 경기)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "87725b2b0a4",
      "name": "크리스탈라인 컨플릭트(화산심장: 친선 경기)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "22ee44f8a9b",
      "name": "크리스탈라인 컨플릭트(절정의 구름: 친선 경기)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "e9b5ac18c58",
      "name": "크리스탈라인 컨플릭트(동방 꼭두각시 어전: 친선 경기)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "11a3aeef3b1",
      "name": "크리스탈라인 컨플릭트(붉은 사막: 친선 경기)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "152bfa99b59",
      "name": "크리스탈라인 컨플릭트(바닷가 전투장: 친선 경기)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "0b4e6e9cdf6",
      "name": "크리스탈라인 컨플릭트(하르모니아 전쟁도서관: 친선 경기)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "291e75e31ab",
      "name": "외곽 유적지대(제압전)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "18938c35622",
      "name": "봉인된 바위섬(쟁탈전)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "2e417cb5df8",
      "name": "영광의 평원(쇄빙전)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "048a2f23dde",
      "name": "온살 하카이르(계절끝 합전)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "6eb7981a9ec",
      "name": "워코 치테(연습전)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "5bafe2aea7c",
      "name": "아스트라갈로스(기공전)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "48542ff6367",
      "name": "숨겨진 보루(기공전)",
      "category": "PvP",
      "expansion": "신생 에오르제아",
      "level": 30,
      "itemLevel": null
    },
    {
      "id": "e715e452d9f",
      "name": "절 바하무트 토벌전",
      "category": "절 레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": null
    },
    {
      "id": "8f3ad9f1740",
      "name": "절 알테마 웨폰 파괴작전",
      "category": "절 레이드",
      "expansion": "홍련의 해방자",
      "level": 70,
      "itemLevel": null
    },
    {
      "id": "c2f78a4fceb",
      "name": "절 알렉산더 토벌전",
      "category": "절 레이드",
      "expansion": "칠흑의 반역자",
      "level": 80,
      "itemLevel": null
    },
    {
      "id": "0f8bbc83f1c",
      "name": "절 용시전쟁",
      "category": "절 레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": null
    },
    {
      "id": "0c244b65479",
      "name": "절 오메가 검증전",
      "category": "절 레이드",
      "expansion": "효월의 종언",
      "level": 90,
      "itemLevel": null
    },
    {
      "id": "5df60c0ec22",
      "name": "절 또 하나의 미래",
      "category": "절 레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": null
    },
    {
      "id": "77f765d8dbd",
      "name": "절 요성난무",
      "category": "절 레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": null
    },
    {
      "id": "27d7e88f28b",
      "name": "멸 어둠의 구름 격투전",
      "category": "멸 연합 레이드",
      "expansion": "황금의 유산",
      "level": 100,
      "itemLevel": 710
    }
  ]
};
